# flake8: noqa: E501

phrases = [
    (
        "attorney, defense, witness, courtroom",
        "адвокат, захист, свідок, зал суду",
        "The attorney prepared the defense while the witness waited in the courtroom",
        "Адвокат готував захист, поки свідок чекав у залі суду",
    ),
    (
        "bride, wedding, reception",
        "наречена, весілля, прийом / зустріч гостей",
        "The bride arrived at the wedding reception in a beautiful dress",
        "Наречена прибула на весільний прийом у красивій сукні",
    ),
    (
        "reception",
        "прийом / зустріч гостей",
        "The wedding reception was held in a beautiful garden",
        "Весільний прийом відбувся в прекрасному саду",
    ),
    (
        "reception",
        "прийом / сприйняття інформації або ідей",
        "The movie received a warm reception from critics",
        "Фільм отримав теплий прийом від критиків.",
    ),
    (
        "reception",
        "прийом / реєстратура / приймальня",
        "Please check in at the reception desk.",
        "Будь ласка, зареєструйтеся на стійці реєстрації.",
    ),
    (
        "bride, groom",
        "наречена, наречений",
        "The bride and groom looked happy on their wedding day.",
        "Наречена і наречений виглядали щасливими у день весілля.",
    ),
    (
        "bride, groom",
        "наречена, наречений",
        "The groom helped the bride with her wedding dress.",
        "Наречений допоміг нареченій з її весільною сукнею.",
    ),
    (
        "exploration, incredible, discovery, species",
        "дослідження, неймовірний, відкриття, види",
        "The exploration led to an incredible discovery of new species",
        "Дослідження призвело до неймовірного відкриття нових видів",
    ),
    (
        "exploration",
        "дослідження",
        "The book is an exploration of human emotions.",
        "Книга є дослідженням людських емоцій.",
    ),
    (
        "sailing, adventure",
        "вітрильний спорт, пригода",
        "Sailing across the ocean was an exciting but dangerous adventure",
        "Плавання через океан було захопливою, але небезпечною пригодою",
    ),
    (
        "abandon, disaster, desperate",
        "покинути, катастрофа, відчайдушний",
        "He had to abandon the house after the disaster left him desperate",
        "Йому довелося покинути будинок після того, як катастрофа привела його у відчай",
    ),
    (
        "acknowledge, sincerely, embarrassed",
        "визнати, щиро, збентежений / відчувати незручно",
        "She acknowledged her mistake sincerely and felt embarrassed",
        "Вона щиро визнала свою помилку і почувалася збентеженою",
    ),
    (
        "afford, vacation, overseas",
        "дозволити собі, відпустка, за кордоном",
        "We cannot afford an overseas vacation with our budget",
        "Ми не можемо дозволити собі відпустку за кордоном з нашим бюджетом",
    ),
    (
        "agenda, mayor",
        "порядок денний, мер",
        "The mayor will discuss the agenda at the meeting",
        "Мер обговорить порядок денний на зустрічі",
    ),
    (
        "amazed, discovery",
        "вражений, відкриття",
        "The scientist was amazed by the discovery during the experiment",
        "Учений був вражений відкриттям під час експерименту",
    ),
    (
        "ambition, determined",
        "честолюбність, рішучий / визначений",
        "His ambition made him determined to reach success",
        "Його честолюбність зробила його рішучим досягти успіху",
    ),
    (
        "ankle, soccer",
        "щиколотка, футбол",
        "He injured his ankle during the soccer match, and it was painful",
        "Він травмував щиколотку під час футбольного матчу, і це було боляче",
    ),
    (
        "annoy, loud, neighbor",
        "дратувати, гучний, сусід",
        "The loud noise from the neighbor annoys me every night",
        "Гучний шум від сусіда дратує мене щоночі",
    ),
    (
        "approximately, kilometer",
        "приблизно, кілометр",
        "The journey is approximately 200 kilometers long",
        "Подорож становить приблизно 200 кілометрів",
    ),
    (
        "April, spring",
        "квітень, весна",
        "April brings warm weather and blooming flowers in spring",
        "Квітень приносить теплу погоду і квітучі квіти навесні",
    ),
    (
        "assignment",
        "завдання / призначення",
        "I must complete my assignment before the deadline",
        "Я повинен завершити своє завдання до кінцевого терміну",
    ),
    (
        "assignment, contribute",
        "завдання / призначення, сприяти / робити внесок",
        "Each assignment contributes to your final score",
        "Кожне завдання впливає на вашу підсумкову оцінку",
    ),
    (
        "contribute",
        "сприяти / робити внесок",
        "They contribute positively to the local community.",
        "Вони роблять позитивний внесок у місцеву громаду.",
    ),
    (
        "associated",
        "пов'язаний / відповідний",
        "This project is associated with a well-known company",
        "Цей проєкт пов’язаний із відомою компанією",
    ),
    (
        "associated",
        "пов'язаний / відповідний",
        "Every variable in a database has an associated data type for storage.",
        "Кожна змінна в базі даних має відповідний тип даних для зберігання.",
    ),
    (
        "attach",
        "долучити / прикріпити",
        "Please attach the document before you send the email",
        "Будь ласка, долучіть документ перед відправленням електронного листа",
    ),
    (
        "attach",
        "долучити / прикріпити",
        "They often attach too much importance to minor details",
        "Вони часто надають занадто великого значення дрібним деталям",
    ),
    (
        "attorney, case, defense",
        "адвокат, справа / випадок, захист",
        "The attorney worked hard to defend his client in the case",
        "Адвокат наполегливо працював, щоб захистити свого клієнта у справі",
    ),
    (
        "attraction, tourism",
        "притяжіння, туризм",
        "The main attraction in the city is very popular among tourists",
        "Головна пам'ятка міста дуже популярна серед туристів",
    ),
    (
        "attraction, statue, has risen to, fame, tourism",
        "притяжіння, статуя, здобув / досяг / піднявся до, слава, туризм",
        "This odd statue has risen to fame and is a popular tourist attraction in the city",
        "Ця дивна статуя здобула популярність і є популярною туристичною визначною пам’яткою міста",
    ),
    (
        "has risen to",
        "здобув / досяг / піднявся до",
        "the number of victims has risen to eight",
        "кількість жертв зросла до 8 осіб",
    ),
    (
        "has risen to",
        "здобув / досяг / піднявся до",
        "The quality of life in the city has risen to the moon in recent years.",
        "Якість життя в місті за останні роки зросла до небачених висот.",
    ),
    (
        "attraction",
        "тяжіння",
        "you can feel the attraction between atoms",
        "ви можете відчути тяжіння між атомами",
    ),
    (
        "August, vacation",
        "серпень, відпустка",
        "August is the perfect time for a vacation at the beach",
        "Серпень — ідеальний час для відпустки на пляжі",
    ),
    (
        "aware",
        "усвідомлювати / обізнаний",
        "He is aware of the danger and stays careful after the warning",
        "Він усвідомлює небезпеку і залишається обережним після попередження",
    ),
    (
        "aware",
        "усвідомлювати / обізнаний",
        "She is socially aware and cares about important issues.",
        "Вона соціально відповідальна і турбується про важливі питання.",
    ),
    (
        "aware",
        "усвідомлювати / обізнаний",
        "Please be aware of the new safety rules.",
        "Будь ласка, майте на увазі нові правила безпеки.",
    ),
    (
        "awesome",
        "дивовижний",
        "Her performance was awesome, and the audience loved her talent",
        "Її виступ був дивовижним, і аудиторія захоплювалася її талантом",
    ),
    (
        "based",
        "на основі",
        "The report is based on reliable research results",
        "Звіт базується на надійних результатах дослідження",
    ),
    (
        "basically",
        "в основному",
        "Basically, the idea is simple to explain",
        "В основному, ідею легко пояснити",
    ),
    (
        "bet",
        "ставка",
        "He placed a bet on the game to win some money",
        "Він зробив ставку на гру, щоб виграти трохи грошей",
    ),
    (
        "blank, exam",
        "порожній / незаповнений, іспит",
        "He stared at the blank paper during the exam, unable to write",
        "Він дивився на чистий аркуш під час іспиту, не знаючи, що писати",
    ),
    (
        "bride, wedding",
        "наречена, весілля",
        "The bride looked happy in her beautiful wedding dress",
        "Наречена виглядала щасливо у своїй красивій весільній сукні",
    ),
    (
        "brilliant",
        "блискучий / яскравий",
        "Her brilliant idea made the project a success",
        "Її блискуча ідея зробила проєкт успішним",
    ),
    (
        "bubble",
        "бульбашка",
        "Children love to blow soap bubbles into the air",
        "Діти люблять надувати мильні бульбашки в повітря",
    ),
    (
        "bullet, stray",
        "куля, бродячий / випадковий",
        "The police warned about the danger of stray bullets",
        "Поліція попередила про небезпеку випадкових куль",
    ),
    (
        "stray",
        "бродячий / випадковий",
        "he promised not to stray far from home",
        "він пообіцяв не відходити далеко від дому",
    ),
    (
        "stray",
        "бродячий / випадковий",
        "She has a soft corner for stray animals",
        "Вона має слабкість до бездомних тварин",
    ),
    (
        "stray",
        "бродячий / випадковий",
        "He often adopts stray animals",
        "Він часто усиновлює бездомних тварин",
    ),
    (
        "abandon",
        "відмовитися",
        "You need to abandon your minority language in favor of this major language",
        "Вам потрібно відмовитися від своєї мови меншини на користь цієї основної мови",
    ),
    # =================================
    (
        "capture, wildlife, amazing",
        "захопити, дика природа, дивовижний",
        "He captured amazing wildlife photos with his camera",
        "Він зробив дивовижні фото дикої природи своєю камерою",
    ),
    (
        "cheat, exam, dishonest",
        "шахраювати / обдурити, іспит, нечесний",
        "Cheating on an exam is dishonest and against the rules",
        "Шахраювати на іспиті – це нечесно і суперечить правилам",
    ),
    (
        "cheat",
        "шахраювати / обдурити",
        "Women cheat with other men",
        "Жінки зраджують з іншими чоловіками",
    ),
    (
        "cite",
        "цитувати",
        "You must cite sources in your research paper",
        "Ви повинні цитувати джерела у своїй дослідницькій статті",
    ),
    (
        "closet, clothes, organize",
        "шафа, одяг, організувати",
        "She cleaned and organized her closet yesterday",
        "Вона вчора прибрала і організувала свою шафу",
    ),
    (
        "clothes, appropriate",
        "одяг, відповідний / належний",
        "Make sure your clothes are appropriate. First appearances are important.",
        "Переконайтеся, що ваш одяг відповідає вимогам. Перше враження має значення.",
    ),
    (
        "clue",
        "підказка / ключ",
        "The detective found a clue to solve the mystery",
        "Детектив знайшов ключ до розгадки таємниці",
    ),
    (
        "clue",
        "підказка / ключ",
        "it may provide a clue to a quantum theory of gravity",
        "це може дати ключ до квантової теорії гравітації",
    ),
    (
        "clue, schedule",
        "підказка / ключ, розклад",
        "He did not have a clue regarding the changes in the schedule",
        "Він гадки не мав про зміни в розкладі",
    ),
    (
        "train, competition",
        "тренувати, змагання",
        "The coach trained the team for the competition",
        "Тренер готував команду до змагання",
    ),
    (
        "safe, lock",
        "сейф, запирати / замок",
        "He forgot the combination to his safe lock",
        "Він забув комбінацію до свого сейфового замка",
    ),
    (
        "commonly, mistake, learner, grammar",
        "зазвичай, помилка, учень, граматика",
        "This is a commonly made grammar mistake among learners",
        "Це поширена граматична помилка серед учнів",
    ),
    (
        "communicate",
        "спілкуватися",
        "He tries to communicate his message clearly",
        "Він намагається чітко передати своє повідомлення",
    ),
    (
        "competitive",
        "конкурентний",
        "She is a highly competitive player who wants to win",
        "Вона дуже конкурентний гравець, який хоче перемогти",
    ),
    (
        "competitor, race",
        "конкурент, гонка",
        "The competitor finished the race very fast",
        "Конкурент дуже швидко фінішував у гонці",
    ),
    (
        "confused, direction, lost",
        "спантеличений, напрямок, загубився",
        "He felt confused about the directions and got lost",
        "Він був спантеличений напрямками і загубився",
    ),
    (
        "contemporary",
        "сучасний / актуальний",
        "A contemporary artist exhibited his painting in the gallery",
        "Сучасний художник виставив свою картину у галереї",
    ),
    (
        "contemporary",
        "сучасний / актуальний",
        "celebrities are important in contemporary American life",
        "Знаменитості важливі в сучасному американському житті",
    ),
    (
        "contemporary",
        "сучасний / актуальний",
        "So these all have contemporary relevance.",
        "Тож усе це має сучасну актуальність",
    ),
    (
        "modern, contemporary",
        "сучасний / іноваційний, сучасний / сьогоденний",
        "The art museum has an exceptional collection of modern and contemporary art.",
        "Художній музей має виняткову колекцію модерністського та сучасного мистецтва.",
    ),
    (
        "contest, participate",
        "конкурс, брати участь",
        "She participated in the contest and won a prize",
        "Вона взяла участь у конкурсі і виграла приз",
    ),
    (
        "contribute, charity, donate",
        "сприяти / робити внесок, благодійність, пожертвувати",
        "He contributes to charity by donating money",
        "Він вносить вклад у благодійність, жертвуючи гроші",
    ),
    (
        "core",
        "основний",
        "Core exercises improve strength and overall health",
        "Основні вправи покращують силу і загальне здоров'я",
    ),
    (
        "criterion",
        "критерій",
        "Quality is the main criterion for judging this choice",
        "Якість – головний критерій для оцінки цього вибору",
    ),
    (
        "crucial, impact",
        "вирішальний, вплив",
        "This decision is crucial and will impact the future",
        "Це вирішальне рішення, яке вплине на майбутнє",
    ),
    (
        "crucial, capture",
        "вирішальний, захопити / зафіксувати",
        "The camera captured crucial evidence of the crime",
        "Камера зафіксувала вирішальні докази злочину",
    ),
    (
        "curly",
        "кучерявий",
        "She has naturally curly hair and loves her style",
        "Вона має натурально кучеряве волосся і любить свій стиль",
    ),
    (
        "curved",
        "вигнутий",
        "The curved road is dangerous, so drive carefully",
        "Вигнута дорога небезпечна, тому їдьте обережно",
    ),
    (
        "December, holiday, celebrate",
        "грудень, свято, святкувати",
        "In December, families celebrate the holiday together",
        "У грудні сім’ї святкують свято разом",
    ),
    (
        "decent, salary",
        "пристойний, зарплата",
        "He found a decent job with a stable salary",
        "Він знайшов пристойну роботу зі стабільною зарплатою",
    ),
    (
        "decent, salary",
        "пристойний, зарплата",
        "I think this product will be a decent option.",
        "Думаю, цей продукт буде гідним варіантом.",
    ),
    (
        "defense, attorney",
        "захист, адвокат",
        "The attorney argued in court for the defense",
        "адвокат сперечався в суді за захист",
    ),
    (
        "definite",
        "точний",
        "I need a definite answer to this question",
        "Мені потрібна точна відповідь на це питання",
    ),
    (
        "definitely, fun, party",
        "безумовно, весело, вечірка",
        "The party was definitely fun, and we enjoyed it",
        "Вечірка була безумовно веселою, і ми нею насолоджувалися",
    ),
    # ==============================================
    (
        "deliberate",
        "навмисний / свідомий",
        "A deliberate plan leads to success",
        "Продуманий план веде до успіху",
    ),
    # It was a deliberate attempt to harm him.
    # (
    #     "deliberate",
    #     "навмисний / свідомий",
    #     # She walked with deliberate steps so as not to stumble.
    # # They deliberated over the issue for several hours.
    # ),
    (
        "deliberate",
        "навмисний / свідомий",
        "She spoke in a slow and deliberate manner.",
        "Вона говорила повільно й обдумано.",
    ),
    (
        "deliberating",
        "навмисний / свідомий",
        "They are deliberating whether to accept the offer.",
        "Вони обдумують, чи прийняти пропозицію.",
    ),
    (
        "deliberate",
        "навмисний / свідомий",
        "We need to deliberate on this issue before making a final decision.",
        "Нам потрібно обміркувати це питання перед остаточним рішенням.",
    ),
    (
        "deliberate, typically",
        "навмисний / свідомий, зазвичай",
        # when they have long-term consequences.",
        "We typically are more deliberate about our decisions",
        # , коли вони мають довгострокові наслідки.",
        "Ми зазвичай більш обдумано підходимо до наших рішень",
    ),
    (
        "departure, flight, delay",
        "відправлення, рейс, затримка",
        "The flight departure was delayed at the airport",
        "Відправлення рейсу було затримано в аеропорту",
    ),
    (
        "depressed, lonely",
        "пригнічений, самотній",
        "She felt depressed and lonely",
        "Вона почувалася пригніченою і самотньою",
    ),
    (
        "depressing",
        "пригнічуючий",
        "The news about the situation was depressing",
        "Новини про ситуацію були пригнічуючими",
    ),
    (
        "desperate, solution",
        "відчайдушний, рішення",
        "He was desperate for help with his problem",
        "Він відчайдушно потребував допомоги у своїй проблемі",
    ),
    (
        "determined",
        "рішучий / визначений",
        "She is determined to achieve her goal",
        "Вона рішуче налаштована досягти своєї мети",
    ),
    (
        "development",
        "розвиток",
        "The project is in the development stage",
        "Проєкт знаходиться на стадії розвитку",
    ),
    (
        "diary, thought",
        "щоденник, думка",
        "She writes her thoughts in a diary daily",
        "Вона щодня записує свої думки у щоденник",
    ),
    (
        "differently, unique",
        "по-іншому, унікальний",
        "He thinks differently and has a unique approach",
        "Він думає по-іншому і має унікальний підхід",
    ),
    (
        "dirt, ground",
        "бруд, земля",
        "There was dirt on his shoes from the ground",
        "На його взутті був бруд із землі",
    ),
    (
        "disadvantage, affect",
        "недолік, впливати",
        "The disadvantage affected the final result",
        "Недолік вплинув на кінцевий результат",
    ),
    (
        "disappointing, expected",
        "розчаровуючий, очікувати",
        "The result was disappointing; I expected better",
        "Результат був розчаровуючим; я очікував кращого",
    ),
    (
        "disaster, severe",
        "катастрофа, серйозний",
        "The natural disaster caused severe damage",
        "Природна катастрофа спричинила серйозні пошкодження",
    ),
    (
        "dishonest, action, lose",
        "нечесний, дія, втратити",
        "A dishonest action can make you lose trust",
        "Нечесна дія може призвести до втрати довіри",
    ),
    (
        "divorced, separate",
        "розлучений, розійтися",
        "They got divorced and started living separate lives.",
        "Вони розлучилися і почали жити окремим життям.",
    ),
    (
        "documentary",
        "документальний фільм",
        "This documentary tells a real-life story",
        "Цей документальний фільм розповідає реальну історію",
    ),
    (
        "donate, charity",
        "жертвувати, благодійність",
        "He donates money to charity to support people",
        "Він жертвує гроші на благодійність, щоб підтримати людей",
    ),
    (
        "dressed, formal, suit",
        "одягнений, формальний, костюм",
        "He was dressed in a suit for the formal event",
        "Він був одягнений у костюм для формальної події",
    ),
    (
        "elevator",
        "ліфт",
        "Press the button to go to the next floor in the elevator",
        "Натисніть кнопку, щоб піднятися на наступний поверх у ліфті",
    ),
    (
        "embarrassed, laugh",
        "збентежений / відчувати незручно, сміятися",
        "He felt embarrassed when people laughed at his mistake",
        "Він відчув збентеження, коли люди сміялися з його помилки",
    ),
    (
        "encounter, stranger",
        "зустріч, незнайомець",
        "She had an unexpected encounter with a stranger",
        "Вона мала несподівану зустріч з незнайомцем",
    ),
    (
        "examination, health",
        "обстеження, здоров'я",
        "The doctor performed a health examination",
        "Лікар провів медичне обстеження",
    ),
    (
        "exhibit, museum, artwork",
        "експонат, музей, твір мистецтва",
        "The museum exhibits many beautiful artworks",
        "У музеї виставлено багато прекрасних творів мистецтва",
    ),
    (
        "exploration, mission, discover",
        "дослідження, місія, відкривати",
        "The space mission focused on exploration and discovery",
        "Космічна місія була зосереджена на дослідженні та відкриттях",
    ),
    (
        "extremely",
        "надзвичайно",
        "The winter was extremely cold this year",
        "Цього року зима була надзвичайно холодною",
    ),
    (
        "facility, patient, treatment",
        "заклад, пацієнт, лікування",
        "The hospital facility provides good treatment for patients",
        "Лікарняний заклад забезпечує гарне лікування для пацієнтів",
    ),
    (
        "false, truth",
        "неправдивий, правда",
        "He believed false information instead of the truth",
        "Він повірив неправдивій інформації замість правди",
    ),
    (
        "farming",
        "фермерство",
        "Farming requires good land to grow crops",
        "Фермерство вимагає гарної землі для вирощування врожаю",
    ),
    # (
    #     "",
    #     "",
    #     "",
    #     "",
    # ),
    # (
    #     "",
    #     "",
    #     "",
    #     "",
    # ),
    # (
    #     "",
    #     "",
    #     "",
    #     "",
    # ),
    # (
    #     "",
    #     "",
    #     "",
    #     "",
    # ),
    # (
    #     "",
    #     "",
    #     "",
    #     "",
    # ),
    # (
    #     "",
    #     "",
    #     "",
    #     "",
    # ),
    # (
    #     "",
    #     "",
    #     "",
    #     "",
    # ),
]
