# flake8: noqa: E501

phrases = [
    # # (
    # #     en_words,
    # #     uk_words,
    # #     en_sentence,
    # #     uk_sentence,
    # # )
    # shorts
    (
        "blanket, curtain",
        "ковдра, штора",
        "She pulled the blanket over herself and drew the curtains.",
        "Вона натягнула на себе ковдру і закрила штори.",
    ),
    (
        "persuade, pursue",
        "переконувати, переслідувати",
        "He tried to persuade her to pursue her dreams",
        "Він намагався переконати її переслідувати свої мрії",
    ),
    (
        "eerie, curtain",
        "моторошний, штора",
        "The wind moved the curtain in an eerie way",
        "Вітер моторошно ворушив штору",
    ),
    (
        "blanket, pursue",
        "ковдра, переслідувати",
        "They carried a blanket as they pursued the trail.",
        "Вони несли ковдру, йдучи по сліду.",
    ),
    (
        "eerie, persuade",
        "моторошний, переконувати",
        "The eerie silence persuaded them to leave quickly",
        "Моторошна тиша переконала їх швидко піти",
    ),
    (
        "curtain, pursue",
        "штора, переслідувати",
        "He peeked behind the curtain to pursue the sound",
        "Він заглянув за штору, щоб прислухатися до звуку.",
    ),
    (
        "blanket, eerie, glow",
        "ковдра, моторошний, світіння",
        "The eerie glow made the blanket seem alive",
        "Моторошне сяйво змусило ковдру здаватися живою",
    ),
    (
        "persuade, blanket",
        "переконувати, ковдра",
        "She persuaded him to bring an extra blanket",
        "Вона переконала його принести додаткову ковдру",
    ),
    (
        "eerie, pursue",
        "моторошний, переслідувати",
        "An eerie howl urged them to pursue the creature",
        "Моторошне виття змусило їх переслідувати істоту",
    ),
    (
        "curtain, blanket",
        "штора, ковдра",
        "She pulled the curtain and grabbed a blanket",
        "Вона потягнула штору і схопила ковдру",
    ),
    (
        "threat, steep",
        "загроза, крутий",
        "The steep path was a threat",
        "Крута стежка була загрозою",
    ),
    (
        "beside, narrow",
        "поруч, вузький",
        "She stood beside the narrow door",
        "Вона стояла поруч з вузькими дверима",
    ),
    (
        "frighten, aunt",
        "налякати, тітка",
        "The noise frightened my aunt",
        "Шум налякав мою тітку",
    ),
    (
        "fancy, lawyer",
        "вишуканий, адвокат",
        "The lawyer wore a fancy suit",
        "Адвокат був у вишуканому костюмі",
    ),
    (
        "failure, modest",
        "провал, скромний",
        "Her failure made her modest",
        "Її провал зробив її скромною",
    ),
    (
        "swing, broad",
        "гойдалка, широкий",
        "The swing hung from a broad tree",
        "Гойдалка висіла на широкому дереві",
    ),
    (
        "reveal, evident",
        "розкривати, очевидний",
        "His smile revealed his evident joy",
        "Його усмішка розкривала його очевидну радість",
    ),
    (
        "thin, clever",
        "тонкий, розумний",
        "The clever cat slipped through a thin gap",
        "Розумний кіт прослизнув через тонку щілину",
    ),
    (
        "shelter, cattle",
        "укриття, худоба",
        "The cattle found shelter in the barn",
        "Худоба знайшла укриття в сараї",
    ),
    (
        "pursue, sight, deer",
        "переслідувати, зір, олень",
        "He pursued the deer in his sight",
        "Він переслідував оленя, який був у нього на виду",
    ),
    (
        "dozen, afterward",
        "дюжина, потім",
        "We baked a dozen pies and ate them afterward",
        "Ми спекли дюжину пирогів і потім їх з'їли",
    ),
    (
        "valley, clay, pottery",
        "долина, глина, гончарство",
        "The valley had rich clay for pottery",
        "Долина була багата на глину для гончарства",
    ),
    (
        "slope, burst",
        "схил, вибухати",
        "Water burst down the steep slope",
        "Вода хлинула вниз по крутому схилу.",
    ),
    (
        "blanket, breath",
        "ковдра, подих",
        "She wrapped in a blanket and took a deep breath",
        "Вона загорнулася в ковдру і зробила глибокий вдих",
    ),
    (
        "pole, beneath",
        "жердина, під",
        "He hid beneath the wooden pole",
        "Він сховався під дерев'яною жердиною",
    ),
    (
        "audience, merchant",
        "аудиторія, торговець",
        "The merchant charmed the audience with his tale",
        "Торговець зачарував аудиторію своєю історією",
    ),
    (
        "persuade, climb",
        "переконати, підніматися",
        "She persuaded him to climb the mountain",
        "Вона переконала його піднятися на гору",
    ),
    (
        "seaside, harvest",
        "узбережжя, врожай",
        "We celebrated the harvest by the seaside",
        "Ми святкували врожай біля узбережжя",
    ),
    # (
    #     "deer, needle",
    #     "олень, голка",
    #     "The deer stepped on a sharp needle",
    #     "Олень наступив на гостру голку",
    # ),
    (
        "nest, principal",
        "гніздо, директор",
        "The principal showed us a bird's nest",
        "Директор показав нам пташине гніздо",
    ),
    (
        "chair, thick",
        "стілець, товстий",
        "He sat on a thick wooden chair",
        "Він сидів на товстому дерев'яному стільці",
    ),
    (
        "council, fence",
        "рада, паркан",
        "The council decided to build a fence",
        "Рада вирішила побудувати паркан",
    ),
    (
        "pot, wooden",
        "горщик, дерев'яний",
        "She placed the pot on a wooden table",
        "Вона поставила горщик на дерев'яний стіл",
    ),
    (
        "faithful, curtain, behind",
        "вірний, штора, позаду",
        "The faithful dog slept behind the curtain",
        "Вірний пес спав за шторою",
    ),
    (
        "cupboard, leather",
        "шафа, шкіра",
        "He stored his leather boots in the cupboard",
        "Він зберігав свої шкіряні чоботи в шафі",
    ),
    (
        "soil, rich",
        "ґрунт, багатий",
        "The soil here is rich and fertile",
        "Ґрунт тут багатий і родючий",
    ),
    (
        "rough, castle",
        "грубий, замок",
        "The rough path led to the old castle",
        "Груба стежка вела до старого замку",
    ),
    (
        "fellow, mud",
        "хлопець, бруд",
        "The fellow fell into the mud while running",
        "Хлопець впав у бруд, коли біг",
    ),
    (
        "tie, struggle",
        "зав'язати, боротьба",
        "He struggled to tie the rope tightly",
        # "Він боровся, щоб міцно зав'язати мотузку",
        "Він з трудом міцно зав'язував мотузку",
    ),
    (
        "craft, riverbank",
        "ремесло, берег річки",
        "They crafted a boat on the riverbank",
        "Вони виготовили човен на березі річки",
    ),
    (
        "trail, timber",
        "стежка, деревина",
        "The trail led to a pile of timber",
        "Стежка вела до купи деревини",
    ),
    (
        "thrill, pouring",
        "трепет, ллється",
        "She was thrilled by the pouring rain",
        "Вона була захоплена дощем, що лився",
    ),
    (
        "glove, confident",
        "рукавичка, впевнений",
        "He put on gloves and felt confident",
        "Він одягнув рукавички і відчув упевненість",
    ),
    (
        "daring, countryside, roam",
        "сміливий, сільська місцевість, блукати",
        "The daring explorer roamed the countryside",
        "Сміливий дослідник блукав сільською місцевістю",
    ),
    (
        "sow, thread, mend",
        "сіяти, нитка, виправити",
        "She used thread to mend her sowing sack",
        "Вона використала нитку, щоб полагодити мішок для сівби",
    ),
    (
        "seed, fabric",
        "насіння, тканина",
        "He wrapped seeds in a piece of fabric",
        "Він загорнув насіння в шматок тканини",
    ),
    # (
    #     "damage, bow",
    #     "пошкодження, лук",
    #     "The bow had slight damage from the fall",
    #     "Лук отримав невеликі пошкодження від падіння",
    # ),
    (
        "fold, fog",
        "скласти, туман",
        "He folded his map in the dense fog",
        "Він склав карту в густому тумані",
    ),
    (
        "pie, pupil",
        "пирог, учeнь",
        "The pupils baked delicious pies together",
        "Учні разом пекли смачні пироги",
    ),
    # ^--
    (
        "reach, curtain, reveal",
        "досягати, завіса, розкрити",
        "She reached for the curtain to reveal the sunlight",
        "Вона потягнулася до штори щоб відкрити сонячне світло",
    ),
    # (
    #     "failure, crop, harvest",
    #     "невдача, посів, урожай",
    #     "Despite the failure of their crops, they hoped for a harvest",
    #     "Незважаючи на невдачу з посівами, вони сподівалися на урожай",
    # ),
    (
        "failure, crop, hopeful",
        "невдача, посів, сповнений надії",
        "Despite the failure of their crops, farmers remained hopeful",
        "Незважаючи на невдачу з посівами, фермери залишалися сповненими надії",
    ),
    (
        "thick, mud, struggle, slope",
        "товстий, бруд, боротьба, схил",
        "He struggled through thick mud on the slope",
        "Він пробивався крізь густий бруд на схилі",
    ),
    (
        "frighten, fellow, beneath, cupboard",
        "налякати, хлопець, під, шафа",
        "The frightened fellow hid beneath the cupboard",
        "Наляканий хлопець сховався під шафою",
    ),
    # (
    #     "dozen, cattle, graze, countryside",
    #     "дюжина, худоба, пастися, сільська місцевість",
    #     "A dozen cattle grazed in the countryside",
    #     "Дюжина худоби паслася в сільській місцевості",
    # ),
    (
        "tied, wooden, pole, swing",
        "зв'язаний, дерев'яний, стовп, гойдалка",
        "She tied a swing to a wooden pole",
        "Вона прив'язала гойдалку до дерев'яного стовпа",
    ),
    (
        "evident, threat",
        "очевидний, загроза",
        "Despite the evident threat of rain",
        "Незважаючи на очевидну загрозу дощу",
    ),
    (
        "sow, seed, muddy, soil",
        "сіяти, насіння, брудний, ґрунт",
        "The farmer sowed seeds in muddy soil",
        "Фермер сіяв насіння у вологий ґрунт",
    ),
    (
        "merchant, fancy, leather, glove",
        "торговець, розкішний, шкіряний, рукавичка",
        "The merchant sold fancy leather gloves",
        "Торговець продавав розкішні шкіряні рукавички",
    ),
    (
        "audience, thrill, daring",
        "глядачі, трепет, сміливий",
        "The audience was thrilled by the daring acrobat's performance",
        "Глядачі були в захваті від виступу сміливого акробата",
    ),
    (
        "fold, thick, blanket, beside",
        "складка, товстий, ковдра, поруч",
        "She folded the thick blanket and placed it beside",
        "Вона склала товсту ковдру і поклала її поруч",
    ),
    # ^--
    (
        "modest, carpenter, chair, craft",
        "скромний, столяр, стілець, ремесло",
        "The modest carpenter crafted a beautiful chair",
        "Скромний столяр виготовив гарне крісло",
    ),
    (
        "storm, villager, seaside, damage",
        "шторм, селянин, узбережжя, пошкодження",
        "After the storm, the villagers gathered at "
        "the seaside to inspect the damage",
        "Після шторму селяни зібралися на березі моря, щоб оглянути збитки",
    ),
    (
        "leaned, steep, breath, climb",
        "нахилився, крутий, дихання, підніматися",
        "He leaned against the steep cliff, catching his breath "
        "after the exhausting climb",
        "Він притулився до крутої скелі, переводячи подих "
        "після виснажливого підйому",
    ),
    (
        "principal, encourage, pupil, participate, fair",
        "директор, заохочувати, учeнь, брати участь, ярмарок",
        "The principal encouraged the pupils to participate in "
        "the science fair",
        "Директор закликав учнів взяти участь у науковому ярмарку",
    ),
    (
        "shelter, sturdy / firm, rough, timber, protect",
        "притулок, міцний, грубий, деревина, захистити",
        "They built a sturdy shelter out of rough timber",
        "Вони побудували міцне укриття з грубої деревини",
    ),
    (
        "cheerful, aunt, dozen, pie",
        "веселий, тітка, дюжина, пиріжок",
        "The cheerful aunt baked a dozen pies for the family gathering",
        "Весела тітка спекла десяток пирогів для сімейних зборів",
    ),
    (
        "castle, stood, steep, hill",
        "замок, стояв, крутий, пагорб",
        "The castle stood on a steep hill",
        "Замок стояв на крутому пагорбі",
    ),
    (
        "frighten, burst, nest",
        "налякати, лопнув, гніздо",
        "The frightened bird burst from its nest",
        "Переляканий птах вирвався з гнізда",
    ),
    (
        "valley, thin, mist",
        "долина, тонкий, туман",
        "The valley was hidden by thin mist",
        "Долина була прихована тонким туманом",
    ),
    (
        "failure, confident, pursue",
        "невдача, впевнений, переслідувати",
        "Despite his failure, he remained confident and "
        "continued to pursue his goals",
        "Незважаючи на свою невдачу, він залишався впевненим і "
        "продовжував йти до своїх цілей",
    ),
    (
        "flower, clay, pot, window",
        "квітка, глина, горщик, вікно",
        "She arranged the flowers in a clay pot and placed it near "
        "the window",
        "Вона поклала квіти в глиняний горщик і поставила біля вікна",
    ),
    (
        "broad, valley, thin, sight, mist, eerie",
        "широкий, долина, тонкий, вид, туман, моторошний",
        "The broad valley was covered in a thin layer of mist, "
        "making the sight both eerie and beautiful",
        "Широка долина була вкрита тонким шаром туману, "
        "що робило видовище одночасно моторошним і прекрасним",
    ),
    (
        "afterward, clever, lawyer, persuade, council",
        "згодом, розумний, юрист, переконати, рада",
        "Afterward, the clever lawyer managed to persuade the council "
        "to reconsider their decision",
        "Згодом спритний юрист зумів переконати раду "
        "переглянути своє рішення",
    ),
    (
        "wooden, fence, stood, beside, narrow, castle",
        "дерев'яний, паркан, стояв, поруч, вузький, замок",
        "The wooden fence stood beside the narrow path, leading to an "
        "old castle",
        "Дерев'яна огорожа стояла біля вузької стежки, що вела до "
        "старого замку",
    ),
    # ---
    (
        "folded, blanket, placed, beside",
        "складений, ковдра, розмістив, поруч",
        "She folded the blanket and placed it beside",
        "Вона склала ковдру і поклала її поруч",
    ),
    (
        "principal, pupil, encourage, study",
        "директор, учeнь, заохочувати, навчання",
        "The principal encouraged pupils to study",
        "Директор заохочував учнів до навчання",
    ),
    (
        "aunt, dozen, cheerful, pie, cupboard",
        "тітка, дюжина, весела, пиріг, шафа",
        "Cheerful aunt baked a dozen pies and stored them in the cupboard",
        "Весела тітка спекла дюжину пирогів і поклала їх у шафу",
    ),
    (
        "threat, avalanche, evident, shelter",
        "загроза, лавина, очевидний, укриття",
        "The evident threat of an avalanche forced them to seek shelter",
        "Очевидна загроза лавини змусила їх шукати укриття",
    ),
    (
        "merchant, glove, leather, fancy",
        "торговець, рукавичка, шкіра, розкішний",
        "The merchant sold fancy leather gloves",
        "Торговець продавав розкішні шкіряні рукавички",
    ),
    (
        "muddy, soil, farmer, seed",
        "брудний, ґрунт, фермер, насіння",
        "The farmer planted seeds in muddy soil",
        "Фермер посадив насіння в брудний ґрунт",
    ),
    (
        "storm, damage, seaside, villager",
        "шторм, пошкодження, узбережжя, селянин",
        "After the storm, villagers fixed seaside damage",
        "Після шторму селяни виправили збитки на узбережжі",
    ),
    (
        "craft, pole, swing, timber",
        "ремесло, жердина, гойдалка, деревина",
        "He crafted a swing from timber",
        "Він виготовив гойдалку з деревини",
    ),
    (
        "audience, thrill, daring, acrobat",
        "глядачі, трепет, сміливий, акробат",
        "The audience was thrilled by the daring acrobat",
        "Глядачі були захоплені сміливим акробатом",
    ),
    (
        "failure, pursue, goal, confident",
        "невдача, переслідувати, ціль, впевнений",
        "He pursued his goals confidently despite failure",
        "Він упевнено переслідував свої цілі, незважаючи на невдачу",
    ),
    (
        "blanket, shelter, beneath, safe",
        "ковдра, укриття, під, безпечний",
        "The blanket kept them safe beneath the shelter",
        "Ковдра захищала їх під укриттям",
    ),
    (
        "mud, slope, climb, struggle",
        "бруд, схил, підніматися, боротьба",
        "He struggled to climb the muddy slope",
        "Він боровся, щоб піднятися на брудний схил",
    ),
    (
        "nest, frighten, bird, burst",
        "гніздо, налякати, птах, вилетів",
        "A frightened bird burst from the nest",
        "Зляканий птах вилетів із гнізда",
    ),
    (
        "pursue, confident, forward",
        "переслідувати, упевнений, вперед",
        "She confidently pursued her dreams",
        "Вона впевнено переслідувала свої мрії",
    ),
    (
        "valley, broad, trail, mist",
        "долина, широка, стежка, туман",
        "The broad trail led through misty valley",
        "Широка стежка вела через туманну долину",
    ),
    (
        "evident, threat, act, quickly",
        "очевидний, загроза, діяти, швидко",
        "The evident threat forced quick action",
        "Очевидна загроза змусила швидко діяти",
    ),
    (
        "pupil, fair",
        "учeнь, ярмарок",
        "Pupils prepared for the science fair",
        "Учні готувалися до наукового ярмарку",
    ),
    # (
    #     "craft, chair, wood, carpenter, sturdy",
    #     "ремесло, стілець, дерево, тесля, міцний",
    #     "The carpenter crafted a sturdy chair",
    #     "Тесля виготовив міцний стілець",
    # ),
    (
        "storm, damage, valley",
        "шторм, пошкодження, долина",
        "The storm caused damage in the valley",
        "Шторм завдав шкоди в долині",
    ),
    (
        "glove, fancy, merchant, sold",
        "рукавичка, розкішні, торговець, продавав",
        "The merchant sold fancy gloves",
        "Торговець продавав розкішні рукавички",
    ),
    (
        "soil, seed, harvest, ready",
        "ґрунт, насіння, врожай, готовий",
        "The soil was ready for seeds",
        "Ґрунт був готовий для насіння",
    ),
    (
        "shelter, timber, protect, villager",
        "укриття, деревина, захистити, селянин",
        "The villagers built a shelter with timber",
        "Селяни побудували укриття з деревини",
    ),
    (
        "crop, valley, fertile, grow",
        "посів, долина, родюча, рости",
        "Crops grew well in the fertile valley",
        "посіви добре росли у родючій долині",
    ),
    (
        "fence, wooden, beside, castle",
        "паркан, дерев'яний, поруч, замок",
        "A wooden fence stood beside the castle",
        "Дерев'яний паркан стояв поруч із замком",
    ),
    (
        "evident, threat, action, fast",
        "очевидний, загроза, дія, швидко",
        "The threat required fast action",
        "Загроза вимагала швидких дій",
    ),
    (
        "flower, pot, clay, painted",
        "квітка, горщик, глина, пофарбований",
        "She painted flowers on the clay pot",
        "Вона намалювала квіти на глиняному горщику",
    ),
    (
        "leaned, steep, breath, tired",
        "нахилився, крутий, дихання, втомлений",
        "He leaned on the steep hill, tired",
        "Він нахилився на крутому пагорбі, втомлений",
    ),
]
