# flake8: noqa: E501

phrases = [
    # 1 ----------------
    (
        "ache, faint, chair",
        "біль, слабкість, стілець",
        "She felt an ache and sat on the chair, feeling faint",
        "Вона відчула біль і сіла на стілець, відчуваючи слабкість",
    ),
    (
        "stick, thick, stretch",
        "палиця, товстий, розтягувати",
        "He used a thick stick to stretch the rope",
        "Він використав товсту палицю, щоб розтягнути мотузку",
    ),
    # (
    #     "hut, damp, grain",
    #     "хатинка, вологий, зерно",
    #     "The damp grain was stored in a small hut",
    #     "Вологе зерно зберігалося в маленькій хатинці",
    # ),
    (
        "needle, cloth, torn, sew",
        "голка, тканина, розірване, шити",
        "She used a needle to sew the torn cloth",
        "Вона використовувала голку, щоб зшити розірвану тканину",
    ),
    (
        "chin, beard, neat",
        "підборіддя, борода, акуратний",
        "His neat beard framed his sharp chin",
        "Його акуратна борода обрамляла гостре підборіддя",
    ),
    # (
    #     "nest, twig, feather",
    #     "гніздо, гілочка, перо",
    #     "The bird built a nest with twigs and feathers",
    #     "Птах побудував гніздо з гілочок та пір'я",
    # ),
    (
        "bathe, creek, faint",
        "купатися, струмок, слабкий",
        "They went to bathe in the faintly flowing creek",
        "Вони пішли купатися в струмку, що слабо тече",
    ),
    (
        "sail, vast, bay",
        "вітрило, широкий, затока",
        "A boat with a white sail crossed the vast bay",
        "Човен із білим вітрилом перетнув широку затоку",
    ),
    (
        "jaw, ache, faint",
        "щелепа, біль, слабкість",
        "His jaw began to ache, and he felt faint",
        "Його щелепа почала боліти, і він відчув слабкість",
    ),
    (
        "pad, pale, damp",
        "подушка, блідий, вологий",
        "She rested her pale face on a damp pad",
        "Вона поклала своє бліде обличчя на вологу подушку",
    ),
    # (
    #     "belt, faint, chin",
    #     "пояс, слабкість, підборіддя",
    #     "The belt around his faint frame rested under his chin",
    #     "Пояс на його слабкому тілі тримався під підборіддям",
    # ),
    # (
    #     "twig, thick, creek",
    #     "гілочка, товстий, струмок",
    #     "A thick twig fell into the creek",
    #     "Товста гілочка впала в струмок",
    # ),
    # (
    #     "hut, grain, damp",
    #     "хатинка, зерно, вологий",
    #     "Grain was kept in the damp hut",
    #     "Зерно зберігалося у вологій хатинці",
    # ),
    (
        "needle, sew, cloth",
        "голка, шити, тканина",
        "She sewed the cloth with a needle",
        "Вона зшивала тканину голкою",
    ),
    # (
    #     "ache, faint, stick",
    #     "біль, слабкість, палиця",
    #     "He leaned on a stick when he felt faint from the ache",
    #     "Він сперся на палицю, коли відчув слабкість через біль",
    # ),
    # (
    #     "vast, bay, sail",
    #     "широкий, затока, вітрило",
    #     "The vast bay looked calm under the white sail",
    #     "Широка затока виглядала спокійною під білим вітрилом",
    # ),
    (
        "stroke, chin, beard, stick",
        "гладити, підборіддя, борода, палиця",
        "He stroked his beard while holding a stick under his chin",
        "Він гладив бороду, тримаючи палицю під підборіддям",
    ),
    # (
    #     "creek, faint, bathe",
    #     "струмок, слабкий, купатися",
    #     "They bathed in the faint flow of the creek",
    #     "Вони купалися у слабкому потоці струмка",
    # ),
    # (
    #     "feather, twig, nest",
    #     "перо, гілочка, гніздо",
    #     "A small feather rested in the bird's nest among twigs",
    #     "Маленьке перо лежало в пташиному гнізді серед гілочок",
    # ),
    # (
    #     "pale, pad, damp",
    #     "блідий, подушка, вологий",
    #     "Her pale face was pressed against a damp pad",
    #     "Її бліде обличчя притиснулося до вологої подушки",
    # ),
    # 2 ----------------
    # (
    #     "twig, damp, grain",
    #     "гілочка, вологий, зерно",
    #     "A twig lay on the damp sack of grain",
    #     "Гілочка лежала на вологому мішку із зерном",
    # ),
    # (
    #     "needle, faint, sew",
    #     "голка, слабкий, шити",
    #     "With faint hands, he tried to sew using a needle",
    #     "Слабкими руками він намагався шити за допомогою голки",
    # ),
    # (
    #     "belt, vast, bay",
    #     "пояс, широкий, затока",
    #     "The belt of land stretched around the vast bay",
    #     "Пояс землі простягався навколо широкої затоки",
    # ),
    # (
    #     "ache, stick, hut",
    #     "біль, палиця, хатинка",
    #     "He rested in the hut, leaning on a stick to ease the ache",
    #     "Він відпочивав у хатинці, спираючись на палицю, щоб полегшити біль",
    # ),
    # (
    #     "sail, creek, pale",
    #     "вітрило, струмок, блідий",
    #     "A pale reflection of the sail appeared in the creek",
    #     "Блідий відбиток вітрила з’явився у струмку",
    # ),
    # (
    #     "beard, chin, damp",
    #     "борода, підборіддя, вологий",
    #     "His damp beard dripped onto his chin",
    #     "Його волога борода капала на підборіддя",
    # ),
    # (
    #     "grain, stick, faint",
    #     "зерно, палиця, слабкий",
    #     "The faint farmer carried a stick to collect grain",
    #     "Слабкий фермер ніс палицю, щоб зібрати зерно",
    # ),
    (
        "creek, feather, floate",
        "струмок, перо, плавати",
        "A bird's feather floated in the creek",
        "Перо птаха плавало у струмку",
    ),
    # (
    #     "needle, hut, sew, torn",
    #     "голка, хатинка, шити, порваний",
    #     "In the hut, she found a needle to sew her torn dress",
    #     "У хатинці вона знайшла голку, щоб зашити своє розірване плаття",
    # ),
    # (
    #     "twig, vast, grain",
    #     "гілочка, широкий, зерно",
    #     "The twig rolled across the vast field of grain",
    #     "Гілочка котилася по широкому полі зерна",
    # ),
    # (
    #     "ache, beard, chin",
    #     "біль, борода, підборіддя",
    #     "The ache in his jaw made him rub his beard and chin",
    #     "Біль у щелепі змусив його потерти бороду та підборіддя",
    # ),
    (
        "belt, sail",
        "пояс, вітрило",
        "The sail was tied tightly with a belt",
        "Вітрило було міцно зав'язане поясом",
    ),
    # (
    #     "hut, faint, twig",
    #     "хатинка, слабкий, гілочка",
    #     "A faint sound came from the twig-covered hut",
    #     "Слабкий звук долинав із хатинки, вкритої гілочками",
    # ),
    # (
    #     "needle, pale, stick",
    #     "голка, блідий, палиця",
    #     "He held a needle and a pale stick in his hands",
    #     "Він тримав у руках голку та бліду палицю",
    # ),
    (
        "grain, creek",
        "зерно, струмок",
        "Sacks of grain stood along the field",
        "Мішки із зерном стояли вздовж поля",
    ),
    # (
    #     "nest, twig, feather",
    #     "гніздо, гілочка, перо",
    #     "The nest was built with tiny twigs and feathers",
    #     "Гніздо було побудоване з маленьких гілочок і пір'я",
    # ),
    (
        "wipe, damp, chin, hut",
        "витирати, вологий, підборіддя, хатинка",
        "He wiped his damp chin inside the hut",
        "Він витер вологе підборіддя в хатинці",
    ),
    # (
    #     "creek, faint, pale",
    #     "струмок, слабкий, блідий",
    #     "The pale traveler sat faintly by the creek",
    #     "Блідий мандрівник сидів, слабкий, біля струмка",
    # ),
    (
        "belt, stick, ache",
        "пояс, палиця, біль",
        "The belt he wore supported his back, easing the ache",
        "Пояс, який він носив, підтримував його спину, полегшуючи біль",
    ),
    # (
    #     "feather, grain, hut",
    #     "перо, зерно, хатинка",
    #     "A feather landed on the sack of grain inside the hut",
    #     "Перо впало на мішок із зерном у хатинці",
    # ),
    # (
    #     "vast, twig, faint",
    #     "широкий, гілочка, слабкий",
    #     "The vast field had faint traces of twigs scattered around",
    #     "На широкому полі були слабкі сліди розкиданих гілочок",
    # ),
    (
        "beard, creek, pale",
        "борода, струмок, блідий",
        "His pale beard reflected in the clear creek water",
        "Його бліда борода відбивалася у прозорій воді струмка",
    ),
    # (
    #     "twig, damp, ache",
    #     "гілочка, вологий, біль",
    #     "He sat on a damp log, trying to ease his ache with a twig",
    #     "Він сидів на вологому полі, намагаючись зняти біль гілочкою",
    # ),
    # (
    #     "grain, faint, sail",
    #     "зерно, слабкий, вітрило",
    #     "The faint wind barely moved the sail above the grain sacks",
    #     "Слабкий вітер ледве рухав вітрило над мішками із зерном",
    # ),
    # (
    #     "needle, vast, twig",
    #     "голка, широкий, гілочка",
    #     "She found a needle under the vast pile of twigs",
    #     "Вона знайшла голку під широкою купою гілочок",
    # ),
    # (
    #     "belt, feather, hut",
    #     "пояс, перо, хатинка",
    #     "He hung his belt and feathered hat in the hut",
    #     "Він повісив свій пояс і капелюх із пір’ям у хатинці",
    # ),
    # (
    #     "damp, chin, pale",
    #     "вологий, підборіддя, блідий",
    #     "His damp handkerchief touched her pale chin",
    #     "Його вологий хустинка торкнувся її блідого підборіддя",
    # ),
    (
        "nest, faint",
        "гніздо, слабкий",
        "The weak bird built a faint nest",
        "Слабкий птах побудував слабке гніздо",
    ),
    # # 3 ----------------
    # (
    #     "twig, shadow, forest",
    #     "гілочка, тінь, ліс",
    #     "A twig fell into the shadow of the forest",
    #     "Гілочка впала в тінь лісу",
    # ),
    # (
    #     "brook, breeze, trail",
    #     "струмок, бриз, стежка",
    #     "The brook followed a narrow trail under the breeze",
    #     "Струмок протікав уздовж вузької стежки під бризом",
    # ),
    # (
    #     "storm, shadow, path",
    #     "шторм, тінь, шлях",
    #     "A shadow stretched across the path during the storm",
    #     "Тінь простягалася по шляху під час шторму",
    # ),
    # (
    #     "sky, twilight, glow",
    #     "небо, сутінки, сяйво",
    #     "The twilight glow filled the evening sky",
    #     "Сяйво сутінків наповнило вечірнє небо",
    # ),
    # (
    #     "light, shadow, trail",
    #     "світло, тінь, стежка",
    #     "The light danced through the shadowy trail",
    #     "Світло танцювало через затінену стежку",
    # ),
    # (
    #     "breeze, meadow, peace",
    #     "бриз, луг, спокій",
    #     "The breeze brought peace to the meadow",
    #     "Бриз приніс спокій на луг",
    # ),
    # (
    #     "trunk, forest, light",
    #     "стовбур, ліс, світло",
    #     "Light reflected on the forest trunk",
    #     "Світло відбивалося від стовбура в лісі",
    # ),
    # (
    #     "brook, valley, flowers",
    #     "струмок, долина, квіти",
    #     "The brook flowed past flowers in the valley",
    #     "Струмок протікав повз квіти в долині",
    # ),
    # (
    #     "shadow, forest, twilight",
    #     "тінь, ліс, сутінки",
    #     "Twilight cast long shadows in the forest",
    #     "Сутінки кидали довгі тіні в лісі",
    # ),
    # (
    #     "storm, sky, clouds",
    #     "шторм, небо, хмари",
    #     "Clouds filled the sky before the storm",
    #     "Хмари заповнили небо перед штормом",
    # ),
    # (
    #     "trail, forest, breeze",
    #     "стежка, ліс, бриз",
    #     "A cool breeze followed the forest trail",
    #     "Холодний бриз слідував за лісовою стежкою",
    # ),
    # (
    #     "twig, brook, flowers",
    #     "гілочка, струмок, квіти",
    #     "A twig floated down the brook past the flowers",
    #     "Гілочка пливла вниз по струмку повз квіти",
    # ),
    # (
    #     "light, meadow, shadow",
    #     "світло, луг, тінь",
    #     "Light and shadow played across the meadow",
    #     "Світло і тінь грали на лузі",
    # ),
    # (
    #     "breeze, trail, valley",
    #     "бриз, стежка, долина",
    #     "The breeze cooled the trail in the valley",
    #     "Бриз охолоджував стежку в долині",
    # ),
    # (
    #     "sky, glow, shadow",
    #     "небо, сяйво, тінь",
    #     "The sky held a soft glow above the shadowy trees",
    #     "Небо сяяло м’яким світлом над затіненими деревами",
    # ),
    # (
    #     "storm, forest, wind",
    #     "шторм, ліс, вітер",
    #     "The wind howled through the forest during the storm",
    #     "Вітер завивав у лісі під час шторму",
    # ),
    # (
    #     "twilight, valley, light",
    #     "сутінки, долина, світло",
    #     "Twilight brought soft light to the valley",
    #     "Сутінки принесли м’яке світло в долину",
    # ),
    # (
    #     "breeze, shadow, peace",
    #     "бриз, тінь, спокій",
    #     "The breeze moved shadows gently, bringing peace",
    #     "Бриз м’яко рухав тіні, приносячи спокій",
    # ),
    # (
    #     "brook, light, path",
    #     "струмок, світло, шлях",
    #     "The brook glimmered in the light along the path",
    #     "Струмок мерехтів у світлі вздовж шляху",
    # ),
    # (
    #     "trail, meadow, flowers",
    #     "стежка, луг, квіти",
    #     "The trail led to a meadow full of flowers",
    #     "Стежка вела до лугу, повного квітів",
    # ),
    # (
    #     "light, forest, glow",
    #     "світло, ліс, сяйво",
    #     "A golden glow shone through the forest light",
    #     "Золотисте сяйво проникало через лісове світло",
    # ),
    # (
    #     "shadow, breeze, sky",
    #     "тінь, бриз, небо",
    #     "Shadows moved quickly with the breeze under the sky",
    #     "Тіні швидко рухалися з бризом під небом",
    # ),
    # (
    #     "twilight, flowers, trail",
    #     "сутінки, квіти, стежка",
    #     "Twilight painted the trail with soft light near the flowers",
    #     "Сутінки освітили стежку м’яким світлом біля квітів",
    # ),
    # (
    #     "meadow, brook, peace",
    #     "луг, струмок, спокій",
    #     "Peaceful water ran through the meadow from the brook",
    #     "Спокійна вода текла через луг від струмка",
    # ),
    # (
    #     "forest, path, wind",
    #     "ліс, шлях, вітер",
    #     "The wind carried leaves along the forest path",
    #     "Вітер ніс листя вздовж лісового шляху",
    # ),
    # (
    #     "light, sky, breeze",
    #     "світло, небо, бриз",
    #     "The breeze carried soft light under the evening sky",
    #     "Бриз ніс м’яке світло під вечірнім небом",
    # ),
    # (
    #     "flowers, meadow, trail",
    #     "квіти, луг, стежка",
    #     "The meadow flowers lined the peaceful trail",
    #     "Квіти на лузі обрамляли спокійну стежку",
    # ),
    # (
    #     "shadow, forest, breeze",
    #     "тінь, ліс, бриз",
    #     "A shadow followed the gentle breeze in the forest",
    #     "Тінь слідувала за легким бризом у лісі",
    # ),
    # (
    #     "trail, valley, brook",
    #     "стежка, долина, струмок",
    #     "The brook joined the valley near the winding trail",
    #     "Струмок з’єднався з долиною біля звивистої стежки",
    # ),
    # 4 ------------------------------------------
    (
        "thirsty, spot, vessel, shore",
        "спраглий, пляма, судно, берег",
        "The thirsty sailor spotted a vessel near the shore",
        "Спраглий моряк помітив судно біля берега",
    ),
    (
        "yard, copper, fence",
        "двір, мідь, паркан",
        "The yard was surrounded by a fence made of copper",
        "Двір був оточений парканом із міді",
    ),
    (
        "cheek, gaze / glance",
        "щока, погляд",
        "She felt her cheek burn under his gaze",
        "Вона відчула, як горить її щока під його поглядом",
    ),
    (
        "drawer, towel, cupboard",
        "шухляда, рушник, шафа",
        "The towel was neatly folded in the cupboard drawer",
        "Рушник був акуратно складений у шухляді шафи",
    ),
    (
        "delight, amuse",
        "радувати, розважати",
        "The clown's tricks delighted and amused the child",
        "Трюки клоуна порадували і розважали дитину",
    ),
    (
        "attract, captivate",
        "приваблювати, захоплювати",
        '"captivate" is to attract and hold interest and attention of',
        '"captivate" означає привернути й утримати інтерес і увагу',
    ),
    (
        "thrilled",
        "у захваті",
        '"thrilled" means very excited and pleased',
        '"в захваті" означає дуже схвильований і задоволений',
    ),
    (
        "delight",
        "радувати",
        '"delight" is to give delight to; to affect with great pleasure',
        '"delight" означає дарувати задоволення; впливати з великим задоволенням',
    ),
    (
        "appeal, appealing, amuse",
        "звернення, привабливий, розважити",
        "To amuse a person is for them to find you funny or comically appealing",
        "Розважити людину означає вважати вас смішним або комічно привабливим",
    ),
    (
        "Entertain",
        "Розважати",
        '"Entertain" means to keep a person interested in what you\'re doing',
        "«Розважати» означає підтримувати інтерес людини до того, що ви робите",
    ),
    # (
    #     "tribe, gesture, respect",
    #     "плем'я, жест, повага",
    #     "The tribe showed respect with a unique gesture",
    #     "Плем'я виявило повагу за допомогою унікального жесту",
    # ),
    (
        "extent, emphasize, boundary",
        "ступінь, підкреслити, межа",
        "The map emphasized the extent of the country's boundaries",
        "Карта підкреслювала протяжність кордонів країни",
    ),
    # (
    #     "straw, barn, livestock",
    #     "солома, сарай, худоба",
    #     "The barn was filled with straw for the livestock",
    #     "Сарай був наповнений соломою для худоби",
    # ),
    (
        "steep, slope, swiftly",
        "крутий, схил, швидко",
        "The creature moved swiftly up the steep slope",
        "Створіння швидко піднімалося крутим схилом",
    ),
    (
        "admire, vast, desert",
        "милуватися / захоплюватися, широкий, пустеля",
        "They admired the beauty of the vast desert",
        "Вони милувалися красою широкої пустелі",
    ),
    (
        "glimpse, shadow, alley",
        "проблиск, тінь, провулок",
        "He caught a glimpse of a shadow moving in the alley",
        "Він побачив проблиск тіні, що рухалася в провулку",
    ),
    (
        "tribe, elder, decision",
        "плем'я, старійшина, рішення",
        "The tribe's elder made a final decision",
        "Старійшина племені прийняв остаточне рішення",
    ),
    (
        "meadow, bloom",
        "луг, цвітіння",
        "Wildflowers bloomed beautifully across the meadow",
        "Польові квіти прекрасно цвіли на лузі",
    ),
    (
        "parcel, delivery, village",
        "посилка, доставка, село",
        "The parcel arrived in the village by a fast delivery",
        "посилка прибула у село швидкою доставкою",
    ),
    # (
    #     "fence, yard, barn",
    #     "паркан, двір, сарай",
    #     "The barn stood behind the wooden fence in the yard",
    #     "Сарай стояв за дерев'яним парканом у дворі",
    # ),
    (
        "stream, bend",
        "потік, вигин",
        "The stream bent around the stones",
        "Потік вигинався навколо каменів",
    ),
    (
        "pitch, team, goal",
        "поле, команда, мета",
        "The team gathered on the pitch to discuss their goal",
        "Команда зібралася на полі, щоб обговорити свою мету",
    ),
    (
        "shade",
        "тінь",
        "The forest offered cool shade in the summer heat",
        "Ліс забезпечував прохолодну тінь у літню спеку",
    ),
    (
        "brook, trail, valley",
        "струмок, стежка, долина",
        "The trail followed a brook through the valley",
        "Стежка йшла за струмком через долину",
    ),
    # (
    #     "gesture, approval, elder",
    #     "жест, схвалення, старійшина",
    #     "The elder nodded in approval at the respectful gesture",
    #     "Старійшина кивнув зі схваленням на поважний жест",
    # ),
    (
        "yard, children, laughter",
        "двір, діти, сміх",
        "The yard was filled with the laughter of children",
        "Двір був наповнений сміхом дітей",
    ),
    (
        "stream, stones, bend",
        "потік, каміння, вигин",
        "The stream flowed over smooth stones at the bend",
        "Потік протікав через гладке каміння на вигині",
    ),
    (
        "tribe, custom, ceremony",
        "плем'я, звичай, церемонія",
        "The tribe followed their old custom during the ceremony",
        "Плем'я дотримувалося свого старого звичаю під час церемонії",
    ),
    (
        "elder, earne, respect, wisdom",
        "старійшина, заробляти, повага, мудрість",
        "The elder was known for his wisdom and earned respect",
        "Старійшина був відомий своєю мудрістю і здобув повагу",
    ),
    # (
    #     "parcel, delivery, barn",
    #     "пакунок, доставка, сарай",
    #     "The delivery included a parcel left near the barn",
    #     "Доставка включала пакунок, залишений біля сараю",
    # ),
    (
        "meadow, thrive",
        "луг, процвітати",
        "The meadow's flowers thrived in the gentle shade",
        "Квіти лугу процвітали в ніжній тіні",
    ),
    (
        "goal, achieve, effort",
        "мета, досягти, зусилля",
        "Their goal was achieved through great effort",
        "Їхня мета була досягнута завдяки великим зусиллям",
    ),
    (
        "gesture, approval",
        "жест, схвалення",
        "He showed approval with a friendly gesture",
        "Він показав схвалення дружнім жестом",
    ),
    # (
    #     "shade, stream, flowers",
    #     "тінь, струмок, квіти",
    #     "The stream ran past flowers under the shade of trees",
    #     "Струмок протікав повз квіти під тінню дерев",
    # ),
    (
        "trail, bend, meadow",
        "стежка, вигин, луг",
        "The trail bent sharply as it entered the meadow",
        "Стежка різко вигиналася, входячи на луг",
    ),
    # 5 ------------------------------
    (
        "virtue, grace, deed",
        "чеснота, грація, вчинок",
        "Her virtue and grace were evident in every deed",
        "Її чеснота та грація були очевидними в кожному вчинку",
    ),
    (
        "boundary, dispute, settle",
        "межа, суперечка, врегулювати",
        "The boundary dispute was finally settled peacefully",
        "Суперечка щодо межі була нарешті врегульована мирно",
    ),
    (
        "cheer, effort, outcome, apparent / obvious / evident",
        "радість, зусилля, результат, очевидний",
        "Their cheer grew as the outcome of their effort became apparent",
        "Їхня радість зростала, коли результат їхніх зусиль став очевидним",
    ),
    (
        "collapse, dwell, rebuild",
        "колапс, мешкати, відновити",
        "After the collapse, they dwelled together to rebuild the village",
        "Після колапсу вони мешкати разом, щоб відновити село",
    ),
    (
        "dwell",
        "зациклюватися зупинятися",
        "Way too many of you dwell on your losses",
        "Занадто багато з вас зациклюються на своїх втратах",
    ),
    (
        "dwell",
        "зациклюватися зупинятися",
        "We won't dwell too much on this",
        "Не будемо на цьому надто зупинятися",
    ),
    (
        "leaf, stem",
        "листок, стебло",
        "The leaf fell gently from the stem of the tree",
        "Листок м’яко впав зі стебла дерева",
    ),
    (
        "trial, accuse, fair",
        "суд, звинувачувати, справедливий",
        "The trial aimed to be fair to those accused",
        "Суд мав на меті бути справедливим до обвинувачених",
    ),
    (
        "grade, achieve",
        "оцінка, досягти",
        "She studied hard to achieve the highest grade",
        "Вона старанно навчалася, щоб досягти найвищої оцінки",
    ),
    (
        "mercy, justice, virtue",
        "милосердя, справедливість, чеснота",
        "Mercy and justice are considered great virtues",
        "Милосердя та справедливість вважаються великими чеснотами",
    ),
    # (
    #     "gesture, approval, unite",
    #     "жест, схвалення, об’єднати",
    #     "The gesture of approval helped unite the team",
    #     "Жест схвалення допоміг об’єднати команду",
    # ),
    (
        "yield, effort, success, worth",
        "віддача, зусилля, успіх, варто",
        "The yield of success was worth the effort",
        "Віддача успіху була варта зусиль",
    ),
    (
        "scale, extend, measure",
        "масштаб, розширити, виміряти",
        "The scale of the project extended as they measured progress",
        "Масштаб проєкту розширювався одночасно з тим, як вони вимірювали прогрес",
    ),
    (
        "barely, perceive, event",
        "ледве, сприймати, подія",
        "He could barely perceive the importance of the event",
        "Він ледве міг сприйняти важливість події",
    ),
    (
        "engage, lively",
        "залучити, жвавий",
        "The lively debate engaged everyone in the room",
        "Жваві дебати залучили всіх у кімнаті",
    ),
    (
        "relieve, ache, recovery",
        "полегшити, біль, одужання",
        "The medicine helped relieve the ache and speed up recovery",
        "Ліки допомогли полегшити біль і прискорити одужання",
    ),
    (
        "prospect, career, advance",
        "перспектива, кар'єра, просування",
        "The prospect of a bright career encouraged her to advance",
        "Перспектива яскравої кар'єри підбадьорила її до просування",
    ),
    (
        "pride, effort, outcome",
        "гордість, зусилля, результат",
        "They took pride in the outcome of their collective effort",
        "Вони пишалися результатом своїх спільних зусиль",
    ),
    (
        "wander, aimless, path",
        "бродити, безцільний, шлях",
        "He wandered aimlessly along the forest path",
        "Він безцільно бродив лісовим шляхом",
    ),
    (
        "threshold, decision",
        "поріг, рішення",
        "Standing on the threshold, she made a life-changing decision",
        "Стоячи на порозі, вона прийняла рішення, яке змінило її життя",
    ),
    (
        "bargain, purchase, trade",
        "угода, покупка, торгівля",
        "The bargain was fair, and the purchase pleased both parties",
        "Угода була справедливою, і покупка задовольнила обидві сторони",
    ),
    (
        "durable, reliable",
        "міцний, надійний",
        "The hammer was crafted from durable steel, a reliable tool",
        "Молоток був виготовлений із міцної сталі, надійний інструмент",
    ),
    (
        "trace, evidence, solve",
        "слід, доказ, розв’язати",
        "They followed every trace of evidence to solve the mystery",
        "Вони слідували за кожним слідом доказів, щоб розкрити таємницю",
    ),
    (
        "retire, years, peace",
        "вийти на пенсію, роки, спокій",
        "After many years, he retired to live in peace",
        "Після багатьох років він вийшов на пенсію, щоб жити в спокої",
    ),
    (
        "assure, safe, journey",
        "запевнити, безпечний, подорож",
        "The guide assured them of a safe journey",
        "Гід запевнив їх у безпеці майбутньої подорожі",
    ),
    (
        "boundary, distinct, secure, ensure",
        "межа, чіткий, безпечний, забезпечити",
        "The boundary was marked to ensure distinct and secure land ownership",
        "Межа була позначена, щоб забезпечити чітку та безпечну власність на землю",
    ),
    (
        "furnish, space, cozy",
        "обставити, простір, затишний",
        "She furnished the small space to make it cozy",
        "Вона обставила маленький простір, щоб зробити його затишним",
    ),
    (
        "extent, flood, measure",
        "ступінь, повінь, виміряти",
        "The extent of the flood damage was difficult to measure",
        "Ступінь пошкодження від повені було важко виміряти",
    ),
    (
        "govern, rule, justice",
        "керувати, правило, справедливість",
        "The leader governed the people with fair rules and justice",
        "Лідер керував народом за допомогою справедливих правил і законів",
    ),
    (
        "evaluate, option, proceed",
        "оцінити, варіант, продовжити",
        "They evaluated every option before deciding how to proceed",
        "Вони оцінили кожен варіант перед тим, як вирішити, як діяти далі",
    ),
    (
        "waste, precious",
        "марнувати, цінний",
        "He realized wasting precious time was his biggest mistake",
        "Він зрозумів, що марнування цінного часу було його найбільшою помилкою",
    ),
    (
        "effort, gain, succeed",
        "зусилля, здобути, досягти успіху",
        "Her efforts helped her gain knowledge and succeed",
        "Її зусилля допомогли їй здобути знання та досягти успіху",
    ),
    # 6 ------------------------------------
    (
        "whistle",
        "свист",
        "He used a whistle to call the dog",
        "Він використав свисток, щоб покликати собаку",
    ),
    (
        "lend, friend",
        "позичити, друг",
        "She agreed to lend her favorite book to a friend",
        "Вона погодилася позичити свою улюблену книгу другові",
    ),
    (
        "nephew, gift, birthday",
        "племінник, подарунок, день народження",
        "They gave a toy car as a gift to their nephew for his birthday",
        "Вони подарували іграшкову машину своєму племіннику на день народження",
    ),
    (
        "towel, dry, shower",
        "рушник, сухий, душ",
        "After the shower, he grabbed a towel to dry himself",
        "Після душу він взяв рушник, щоб витертися",
    ),
    (
        "stove, kitchen, cook",
        "плита, кухня, готувати",
        "The stove in the kitchen was used to cook dinner",
        "плита на кухні слугувала для приготування вечері",
    ),
    (
        "seed, grow, plant",
        "насіння, рости, рослина",
        "The seed was planted and began to grow",
        "Насіння було посаджене і почало рости",
    ),
    (
        "clothe, warmth",
        "одягати, тепло",
        "They clothed the children warmly for the winter",
        "Вони тепло одягли дітей на зиму",
    ),
    (
        "cheek",
        "щока",
        "The mother kissed her child on the cheek",
        "Мати поцілувала дитину в щоку",
    ),
    (
        "mill, grain, flour",
        "млин, зерно, борошно",
        "The old mill turned grain into flour",
        "Старий млин перемелював зерно на борошно",
    ),
    (
        "cart, wheels, market",
        "візок, колеса, ринок",
        "The cart with large wheels was loaded with goods for the market",
        "Візок із великими колесами був завантажений товарами для ринку",
    ),
    (
        "adviser, decision, guidance",
        "радник, рішення, вказівки",
        "The adviser provided guidance for the difficult decision",
        "Радник надав вказівки для прийняття складного рішення",
    ),
    (
        "extensive, survey, findings",
        "обширний, опитування, результати",
        "The extensive survey revealed surprising findings",
        "Обширне опитування виявило несподівані результати",
    ),
    (
        "vowel, sound",
        "голосний, звук",
        "The vowel sound was distinct in this language",
        "Голосний звук був чітким у цій мові",
    ),
    # (
    #     "steel, build",
    #     "сталь, будувати",
    #     "They used steel tools to build the structure",
    #     "Вони використовували сталеві інструменти для будівництва конструкції",
    # ),
    (
        "goal, achieve, reward",
        "мета, досягти, нагорода",
        "Reaching the goal was its own reward",
        "Досягнення мети було само нагородою",
    ),
    (
        "shade",
        "тінь",
        "They sat in the shade to relax during the summer heat",
        "Вони сиділи в тіні, щоб розслабитися під час літньої спеки",
    ),
    (
        "gesture, guest",
        "жест, гість",
        "The host made a kind gesture to welcome the guest",
        "Господар зробив доброзичливий жест, щоб привітати гостя",
    ),
    (
        "stream, clear, sparkling",
        "потік, прозорий, ігристе блискучий",
        "The stream was filled with clear, sparkling water",
        "Потік був наповнений прозорою, блискучою водою",
    ),
    (
        "emphasize, point, explain",
        "підкреслити, точка, пояснити",
        "She emphasized the main point to explain the concept",
        "Вона підкреслила головну точку, щоб пояснити концепцію",
    ),
    (
        "barely, manage",
        "ледве, впоратися",
        "He barely managed to finish his work on time",
        "Він ледве впорався із завершенням своєї роботи вчасно",
    ),
    (
        "wander, explore",
        "бродити, досліджувати",
        "They wandered aimlessly to explore the forest paths",
        "Вони безцільно бродили, досліджуючи стежки лісу",
    ),
    (
        "lend, support",
        "позичити, підтримка",
        "He was ready to lend his support to a friend in need",
        "Він був готовий надати підтримку другові в потребі",
    ),
    (
        "stream, flow, rocks",
        "потік, текти, каміння",
        "The stream flowed gently over the smooth rocks",
        "Потік плавно протікав через гладке каміння",
    ),
    (
        "gesture, elder",
        "жест, старійшина",
        "They made a gesture of respect toward the elder",
        "Вони зробили жест поваги до старійшини",
    ),
    (
        "towel",
        "рушник",
        "He dried his face with a towel",
        "Він витер обличчя рушником",
    ),
    (
        "adventure, story, inspire",
        "пригоди, історія, надихати",
        "The adventure story inspired the children to dream big",
        "Історія про пригоди надихнула дітей мріяти масштабно",
    ),
    (
        "seed, nurture, grow",
        "насіння, плекати, рости",
        "If you nurture the seed, it will grow into a strong plant",
        "Якщо ви плекаєте насіння, воно виросте в міцну рослину",
    ),
    # (
    #     "shade, tree, cool",
    #     "тінь, дерево, прохолодний",
    #     "They sat under the shade of the tree to stay cool",
    #     "Вони сиділи під тінню дерева, щоб залишатися прохолодними",
    # ),
    (
        "goal, strive, achieve",
        "мета, прагнути, досягти",
        "She always strives to achieve her goal",
        "Вона завжди прагне досягти своєї мети",
    ),
    (
        "strive, steady, ensure, growth",
        "прагнути, стабільне, забезпечити, зростання",
        "We must strive to ensure steady growth",
        "Ми повинні прагнути забезпечити стабільне зростання",
    ),
]
