# flake8: noqa: E501

phrases = [
    # # https://www.youtube.com/shorts/N_T1xC_XA60
    (
        "refrain, calm",
        "утриматися, спокій",
        "He had to refrain from making a speech to keep the calm",
        "Йому довелося утриматися від промови, щоб зберегти спокій",
    ),
    (
        "refrain, retain",
        "утриматися, зберігати",
        "refrain from violence but retain a radical worldview",
        "утримуватися від насильства, але зберігати радикальний світогляд",
    ),
    (
        "refrain",
        "утриматися",
        "Normally I refrain from alcohol",
        "Зазвичай я утримуюся від алкоголю",
    ),
    # (
    #     "proverbial, wisdom, elders",
    #     "прислів'я, мудрість, старійшини",
    #     "The proverbial wisdom of the elders guided the tribe",
    #     "Прислівна мудрість старійшин керувала племенем",
    # ),
    # (
    #     "thumbs, signal, approval",
    #     "великі пальці, сигнал, схвалення",
    #     "He gave a thumbs-up as a signal of approval",
    #     "Він показав великий палець догори як знак схвалення",
    # ),
    # (
    #     "soak, rain, clothes",
    #     "промокнути, дощ, одяг",
    #     "The heavy rain caused his clothes to soak completely",
    #     "Сильний дощ повністю промочив його одяг",
    # ),
    (
        "digest",
        "засвоювати",
        "They can live in our digestive system and help us digest our food",
        "Вони можуть жити в нашій травній системі і допомагати нам засвоювати їжу.",
    ),
    (
        "digest",
        "засвоювати",
        "She quickly digested the knowledge from the book",
        "Вона швидко засвоїла знання з книги",
    ),
    (
        "digest",
        "перетравлювати",
        "She digested the book thoroughly",
        "Вона повністю засвоїла знання з книги",
    ),
    # # ^-----------
    # # пагано запам'ятав у 2-гому наборі вправ
    # (
    #     # strive,
    #     # evidence,
    #     # appealing,
    #     # extensive,
    #     # extent,
    #     # extend,
    #     # thrive,
    #     # steady,
    #     # faint,
    #     # cheer,
    #     # brook,
    #     # shade,
    #     # giving Medicare the authority to bargain.
    #     # labor that is able to bargain collectively.
    #     # when they don't live up to their end of the bargain.
    #     # .
    #     # This is not the bargain I wanted to make.
    # # ^--
    (
        "trial",
        "судовий розляд",
        "the case went to trial, and he was found guilty.",
        "справу передали до суду, і його визнали винним.",
    ),
    (
        "trial",
        "судовий розляд",
        "The trial lasted for three weeks",
        "Судовий процес тривав три тижні",
    ),
    (
        "trial",
        "спроба",
        "Innovations are the result, usually, of trial and error.",
        "Інновації, як правило, є результатом проб і помилок.",
    ),
    (
        "bargain, authority",
        "торгуватися, повноваження",
        "He has the authority to bargain for us",
        "У нього є право вести переговори за нас",
    ),
    (
        "bargain",
        "торгуватися",
        "People bargain to achieve efficient outcomes",
        "Люди торгуються, щоб досягти ефективних результатів",
    ),
    (
        "bench, drawer, assembly",
        "верстат, ящик, монтажний",
        "I made a bunch of drawers for this assembly bench",
        "Я зробив багато ящиків для цього монтажного верстата",
    ),
    (
        "bench",
        "лавка",
        "I transitioned from a bench biochemist to a data scientist.",
        "Я перейшов від лабораторного біохіміка до дата-саєнтиста",
    ),
    (
        "spoil, mood, rude",
        "зіпсувати, настрій, грубий",
        "The rude comment spoiled her mood during the party",
        "Грубий коментар зіпсував їй настрій на вечірці",
    ),
    # (
    #     "springs, spoil, saturated, prone, slide",
    #     "джерела, ґрунт (або відходи), насичений, схильний, зсуватися",
    #     "These springs have led the spoil to become saturated and prone to slide",
    #     "Ці джерела призвели до того, що ґрунт став насиченим і схильним до зсуву",
    # ),
    # """"""""""""""""""""""""""""""""""""""""
    (
        "injury",
        "травма",
        "He gave away a big spoiler about the movie's ending",
        "Він розкрив великий спойлер про закінчення фільму",
    ),
    (
        "ruined",
        "зіпсувати",
        "The spoiler completely ruined the surprise for me",
        "Спойлер повністю зіпсував для мене сюрприз",
    ),
    (
        "grandparent, spoil, grandchildren",
        "бабуся обо дідусь, балувати, онуки",
        "Grandparents often spoil their grandchildren",
        "Бабусі й дідусі часто балують своїх онуків",
    ),
    (
        "spoil, excavation, dumped",
        "відходи, розкопки, викинуті",
        "The spoil from the excavation was dumped nearby",
        "Відходи від розкопок були викинуті поруч",
    ),
    (
        "spoil, mood",
        "псувати, настрій",
        "Don't let the rain spoil your mood",
        "Не дозволяй дощу зіпсувати твій настрій",
    ),
    (
        "soil, fertile",
        "грунт, родючий",
        "The soil in this region is very fertile",
        "Грунт у цьому регіоні дуже родючий",
    ),
    (
        "soiled, hike",
        "забруднив, похід",
        "He soiled his clothes during the hike",
        "Він забруднив одяг під час походу",
    ),
    (
        "spoil, mine, fertile, soil",
        "відходи, шахта, родючий, грунт",
        "The spoil from the mine covered the fertile soil",
        "Відходи з шахти вкрили родючий грунт",
    ),
    (
        "greet, doorway",
        "привітати, дверний отвір",
        "He made a warm gesture to greet her at the doorway",
        "Він зробив теплий жест, щоб привітати її у дверях",
    ),
    (
        "withdraw",
        "зняти",
        "She withdrew money from her savings account",
        "Вона зняла гроші зі свого рахунку заощаджень",
    ),
    (
        "withdraw",
        "відступити",
        "Israel agreed to withdraw from the Sinai",
        "Ізраїль погодився вийти з Синайського",
    ),
    (
        "withdraw",
        "відступити",
        "Withdraw from the Paris Agreement",
        "Вийти з Паризької угоди",
    ),
    (
        "confidence, audience",
        "впевненість, аудиторія",
        "His confident speech inspired the audience",
        "Його впевнена промова надихнула аудиторію",
    ),
    (
        "confidence, challenge",
        "впевненість, виклик",
        "These challenges have damaged confidence",
        "Ці виклики підірвали впевненість",
    ),
    (
        "confidence, underestimate, importance",
        "впевненість, недооцінювати, важливість",
        "Confidence is something whose importance we tend to underestimate",
        "Впевненість — це те, важливість чого ми схильні недооцінювати",
    ),
    # (
    #     "fig",
    #     "інжир",
    #     "The fig tree in the garden produces sweet fruit",
    #     "Дерево інжиру в саду дає солодкі фрукти",
    # ),
    # (
    #     "plough, planting",
    #     "орати, садіння",
    #     "The farmer ploughed the field to prepare it for planting",
    #     "Фермер зорав поле, щоб підготувати його до садіння",
    # ),
    (
        "ladder",
        "драбина",
        "He used a ladder to climb onto the roof",
        "Він використав драбину, щоб піднятися на дах",
    ),
    (
        "stiff, envelope",
        "жорсткий, конверт",
        "The stiff paper was folded neatly into an envelope",
        "Жорсткий папір був акуратно складений у конверт",
    ),
    (
        "stiff",
        "жорсткий",
        "She battled stiff currents to do this",
        "Вона боролася з сильними течіями, щоб зробити це",
    ),
    (
        "stiff",
        "жорсткий",
        "You might feel stiff or something like that.",
        "Ви можете відчувати скутість або щось подібне.",
    ),
    (
        "stiff, encumber",
        "жорсткий, обтяжувати",
        "When you're working in a space suit your hands are encumbered by thick, stiff gloves.",
        "Коли ви працюєте в скафандрі, ваші руки обтяжені товстими, жорсткими рукавичками.",
    ),
    (
        "pan",
        "сковорода",
        "She used a pan to fry eggs for breakfast",
        "Вона використала сковороду, щоб посмажити яйця на сніданок",
    ),
    # (
    #     "tin, lid",
    #     "бляшанка, кришка",
    #     "She opened the cupboard to find a tin with a missing lid",
    #     "Вона відкрила шафу, щоб знайти бляшанку без кришки",
    # ),
    # Передає об'єкт загрози або щось, що наближається.
    (
        "threaten, approach",
        "загрожувати, наближення",
        "The sky threatened an approaching storm",
        "Небо загрожувало наближенням шторму",
    ),
    (
        "threaten",
        "загрожувати",
        "The announcement threatened the stability of the company.",
        "Оголошення поставило під загрозу стабільність компанії.",
    ),
    # Вказує на джерело загрози (у пасивному реченні).
    (
        "threaten",
        "загрожувати",
        "The village was threatened by the flood.",
        "Селу загрожувала повінь",
    ),
    # Описує засіб, знаряддя або спосіб загрози.
    (
        "threaten",
        "загрожувати",
        "The man threatened her with harsh consequences.",
        "Чоловік погрожував їй тяжкими наслідками.",
    ),
    # ^--
    (
        "permit, hall",
        "дозвіл, зала",
        "A permit is required for entry into the conference hall",
        "Для входу до зали конференції потрібен дозвіл",
    ),
    (
        "substantial, satisfied",
        "суттєвий, задоволений",
        "After a substantial meal, his hunger was fully satisfied",
        "Після ситної їжі його голод був повністю задоволений",
    ),
    (
        "quote",
        "цитувати",
        "The company provided a detailed quote for the project price",
        "Компанія надала детальну пропозицію щодо ціни проекту",
    ),
    (
        "bond",
        "зв'язок - узи",
        "Their bond of trust made their friendship stronger",
        "Їхні узи довіри зробили їхню дружбу міцнішою",
    ),
    (
        "bond",
        "зв'язок - узи",
        "parents have a genetic bond about their children",
        "батьки мають генетичний зв’язок зі своїми дітьми",
    ),
    (
        "tight, knot, secure",
        "щільний, вузол, закріпити",
        "He tied a tight knot to secure the rope",
        "Він зав'язав щільний вузол, щоб закріпити мотузку",
    ),
    (
        "plural, noun",
        "множина, іменник",
        "The teacher explained plural nouns in the grammar lesson",
        "Вчитель пояснив множину іменників на уроці граматики",
    ),
    (
        "defendant, deny, accusation, strongly, court",
        "відповідач, заперечувати, звинувачення, міцно, суд",
        "The defendant strongly denied the accusation in court",
        "Обвинувачений рішуче заперечив звинувачення в суді",
    ),
    (
        "offend, remark, sensitive, unintended",
        "ображати, зауваження, чутливий, ненавмисний",
        "Her remark unintentionally offended his sensitive nature",
        "Її зауваження ненавмисно образило його чутливу натуру",
    ),
    (
        "possess, impressive",
        "володіти, вражаючий",
        "She possesses an impressive talent for creativity",
        "Вона володіє вражаючим талантом до креативності",
    ),
    (
        "sheet, scribble",
        "аркуш, писати",
        "He scribbled notes on a sheet of paper during the lecture",
        "Він писав нотатки на аркуші паперу під час лекції",
    ),
    (
        "scribble",
        "нашкрябати",
        "Scribble out a few words on a piece of paper",
        "Нашкрябати кілька слів на шматку паперу",
    ),
    (
        "stare",
        "витріщатися",
        "She stared out of the window as the rain was pouring down",
        "Вона витріщилася у вікно на те як лив дощ",
    ),
    (
        "disturb, hallway",
        "турбувати, коридор",
        "The noise from the hallway disturbed her sleep",
        "Шум із коридору потривожив її сон",
    ),
    (
        "scatter",
        "розкидати",
        "He scattered the seeds in the garden carefully",
        "Він обережно розкидав насіння в саду",
    ),
    (
        "wage",
        "зарплата",
        "He worked hard to earn his weekly wage",
        "Він наполегливо працював, щоб заробити свою тижневу зарплату",
    ),
    (
        "chalk",
        "крейда",
        "The teacher used chalk to draw diagrams on the board",
        "Учитель використовував крейду, щоб намалювати діаграми на дошці",
    ),
    (
        "supper, enjoy, hearty",
        "вечеря,насолоджуватися, ситний",
        "The family enjoyed a hearty supper together",
        "Сім'я насолоджувалася ситною вечерею разом",
    ),
    (
        "lean",
        "спиратися",
        "He leaned against the wall to rest for a moment",
        "Він сперся на стіну, щоб трохи відпочити",
    ),
    (
        "compose",
        "складати",
        "She composed beautiful music on the piano",
        "Вона склала чудову музику на піаніно",
    ),
    # 3 part ---------------------------
    (
        "funeral, mourn",
        "похорон, оплакувати",
        "They gathered at the funeral to mourn their lost relative",
        "Вони зібралися на похороні, щоб оплакати свого покійного родича",
    ),
    (
        "confidence, improve, gradually",
        "впевненість, покращити, поступово",
        "Her confidence in public speech improved gradually over time",
        "Її впевненість у публічних виступах поступово покращувалася з часом",
    ),
    (
        "improve, practicing",
        "покращити, практикувати",
        "She improved her skills by practicing public speaking",
        "Вона покращила свої навички, практикуючи публічні виступи",
    ),
    (
        "enhance",
        "покращити",
        "She enhanced her presentation by adding visuals",
        "Вона зробила свою презентацію більш ефектною, додавши візуалізації",
    ),
    (
        "out of spite, anger, unreasonable",
        "зі злості, гнів, безпідставний",
        "He acted out of spite, letting his anger take control",
        "Він діяв зі злості, дозволяючи гніву керувати ним",
    ),
    (
        "out of spite",
        "зі злості",
        "He did it out of spite",
        "Він зробив це зі злості",
    ),
    (
        "spited, neighbor, driveway",
        "насолити / зробити щось із злістю, сусід, під’їзд",
        "She spited her neighbor by blocking his driveway",
        "Вона насолила своєму сусідові, заблокувавши його під’їзд",
    ),
    (
        "in spite of",
        "незважаючи",
        "In spite of these advances, people kept getting lost.",
        "Незважаючи на цей прогрес, люди продовжували губитися.",
    ),
    (
        "gut, in spite of",
        "кишківник, незважаючи",
        "Trust your gut in spite of what the facts may be telling.",
        "Довіряй своїй інтуїції, незважаючи на те, що можуть говорити факти.",
    ),
    (
        "scatter",
        "розкидати",
        "we use the wall to scatter light around the corner",
        "ми використовуємо стіну, щоб розсіювати світло за кутом",
    ),
    (
        "scatter",
        "розкидати",
        "They are scattered and almost impossible to unite.",
        "Вони розкидані і майже неможливо об'єднати.",
    ),
    (
        "scatter, ground, substance",
        "розкидати, земля - основа, речовина",
        "Immune cells scattered around the ground substance.",
        "Імунні клітини розкидані по основній речовині.",
    ),
    # (
    #     "cloth, wipe",
    #     "тканина, витирати",
    #     "She used a cloth to wipe the table clean",
    #     "Вона використала тканину, щоб витерти стіл до чистоти",
    # ),
    (
        "judge, impartially",
        "суддя, неупереджено",
        "The judge decided the case fairly and impartially",
        "Суддя справедливо й неупереджено вирішив справу",
    ),
    (
        "approach, bias",
        "підхід, упередження",
        "She approaches life without bias, treating everyone equally.",
        "Вона підходить до життя без упереджень, ставлячись до всіх однаково.",
    ),
    (
        "borrow, deadline",
        "позичати, термін",
        "He borrowed a book with a two-week deadline",
        "Він позичив книгу на два тижні",
    ),
    # (
    #     "numeral, equation",
    #     "цифра, рівняння",
    #     "She carefully solved the equation using the given numerals",
    #     "Вона обережно розв’язала рівняння, використовуючи задані цифри",
    # ),
    # (
    #     "stiff",
    #     "скований",
    #     "His movements were stiff in the cold morning air",
    #     "Його рухи були скованими через холодне ранкое повітря",
    # ),
    (
        "wheat, grind, flour",
        "пшениця, молоти, борошно",
        "The mill ground the wheat into flour for baking",
        "Млин змолов пшеницю на борошно для випічки",
    ),
    (
        "neglect, duty, consequences, severe",
        "нехтувати, обов’язок, наслідки, серйозний",
        "Neglecting his duties led to severe consequences",
        "Нехтування своїми обов’язками призвело до серйозних наслідків",
    ),
    (
        "neglect",
        "нехтування",
        "The number one reason you lose a client is neglect.",
        "Найголовніша причина втрати клієнта — це нехтування.",
    ),
    (
        "neglect, suddenly",
        "нехтувати, раптово",
        "Suddenly, I couldn't neglect my conflict anymore.",
        "Раптово я більше не міг нехтувати своїм конфліктом.",
    ),
    (
        "wrestling, neglect, embarrassment",
        "боротися, нехтування, збентеження",
        "You're wrestling with feelings of neglect and embarrassment.",
        "Ви боретеся з почуттям нехтування і збентеження.",
    ),
    (
        "emerge, suddenly",
        "з’являтися, раптово",
        "A figure emerged from the shadow in the alley suddenly",
        "Фігура раптово з’явилася з тіні в провулку",
    ),
    (
        "emerge",
        "з'являтися",
        "We can see how organisms emerge and grow",
        "Ми можемо бачити, як організми з'являються та ростуть",
    ),
    (
        "emerge",
        "з'являтися",
        "It emerges from our experiences around money",
        "Воно з'являється з нашого досвіду, пов'язаного з грошима",
    ),
    (
        "foundation, due",
        "основа, належно",
        "The structure collapsed due to its weak foundation",
        "Структура зруйнувалася через слабку основу",
    ),
    (
        "retain, vivid",
        "зберігати, яскравий",
        "She retained a vivid memory of that day even after years",
        "Вона зберігала яскраву пам’ять про той день навіть через роки",
    ),
    (
        "retain",
        "зберігати",
        "Retain a child's eye view of what might be",
        "Зберігати погляд дитини на те, що може бути",
    ),
    (
        "retain",
        "зберігати",
        "You're helping them retain their independence",
        "Ви допомагаєте їм зберігати їхню незалежність",
    ),
    (
        "vivid, gutted",
        "яскраві, спустошені",
        "Vast, vivid landscapes are being gutted",
        "Широкі, яскраві краєвиди спустошуються",
    ),
    (
        "vivid",
        "яскрава",
        "I have a very vivid imagination.",
        "У мене дуже яскрава уява.",
    ),
    (
        "vivid",
        "яскраві",
        "Memories linked to smells are often stronger and more vivid.",
        "Спогади, пов’язані із запахами, часто сильніші та яскравіші.",
    ),
    (
        "anxiety, approach",
        "тривога, наближення",
        "He felt anxiety as the exam date approached",
        "Він відчував тривогу, коли наближався день іспиту",
    ),
    (
        "anxiety, reduce",
        "тривога, зменшити",
        "that practice really reduces my anxiety",
        "ця практика справді зменшує мою тривогу",
    ),
    (
        "struggle, steep, hill",
        "боротися, крутий, пагорб",
        "She struggled to climb the steep hill",
        "Вона боролася, щоб піднятися на крутий пагорб",
    ),
    (
        "descend, stairs, quietly, basement",
        "спускатися, сходи, тихо, підвал",
        "He descended the stairs quietly into the basement",
        "Він тихо спустився сходами у підвал",
    ),
    (
        "customs, inspect, luggage",
        "митниця, оглядати, багаж",
        "The customs officer inspected their luggage at the airport",
        "Митний офіцер оглянув їхній багаж у аеропорту",
    ),
    (
        "permit, application, submit, deadline",
        "дозвіл, заява, подавати / надіслати, термін",
        "He submitted the permit application before the deadline",
        "Він подав заяву на дозвіл до закінчення терміну",
    ),
    # (
    #     "compose",
    #     "складати",
    #     "She composed the message carefully before sending it",
    #     "Вона обережно склала повідомлення перед відправкою",
    # ),
    (
        "torch, cave",
        "факел, печера",
        "They used a torch to light the cave while exploring",
        "Вони використовували факел, щоб освітити печеру під час дослідження",
    ),
    (
        "emphasis, pronunciation",
        "наголос, вимова",
        "The teacher emphasized the correct pronunciation of words.",
        "Учитель робив акцент на правильній вимові слів",
    ),
    (
        "rough, unpleasant",
        "грубий, неприємний",
        "The rough surface felt unpleasant to touch",
        "Шорстка поверхня здавалася неприємною на дотик",
    ),
    (
        "harbor, dock, safely",
        "гавань, причалювати, безпечно",
        "The boats docked safely in the harbor",
        "Човни безпечно причалили до гавані",
    ),
    (
        "deny, claim, firmly, prove",
        "заперечувати, твердження, рішуче, довести",
        "He denied the claim firmly and asked for proof",
        "Він рішуче заперечив твердження та попросив докази",
    ),
    # ^--
    # 4 part --------------------------
    (
        "favor, majority",
        "користь, більшість",
        "The majority voted in favor of the decision",
        "Більшість проголосувала за підтримку рішення",
    ),
    (
        "favor",
        "прихильність",
        "in good favor in many parts of the world",
        "популярна в багатьох частинах світу",
    ),
    (
        "slant, favor",
        "нахиляти, користь",
        "They try to slant it in the favor of the students",
        "Вони намагаються схилити це на користь студентів",
    ),
    # (
    #     "fold, clothes, neatly, drawer",
    #     "складати, одяг, акуратно, ящик",
    #     "She folded the clothes neatly and placed them in the drawer",
    #     "Вона акуратно склала одяг і поклала його в ящик",
    # ),
    # (
    #     "measure, distance, accurately, tools",
    #     "вимірювати, відстань, точно, інструменти",
    #     "They measured the distance accurately using special tools",
    #     "Вони точно виміряли відстань, використовуючи спеціальні інструменти",
    # ),
    # (
    #     "mirror, reflection, clear, shine",
    #     "дзеркало, відображення, чіткий, блищати",
    #     "The mirror showed a clear reflection after being polished",
    #     "Дзеркало показало чітке відображення після полірування",
    # ),
    # (
    #     "panic, noise, crowd, sudden",
    #     "паніка, шум, натовп, раптовий",
    #     "The sudden noise caused panic in the crowd",
    #     "Раптовий шум викликав паніку в натовпі",
    # ),
    (
        "in time - on time",
        "вчасно",
        "'in time' means 'before it's too late'",
        "«in time» означає «поки не пізно»",
    ),
    (
        "in time - on time",
        "вчасно",
        "He rescued the child from the river just in time",
        "Він врятував дитину з річки вчасно",
    ),
    (
        "in time - on time",
        "вчасно",
        "'on time' means 'at the arranged or correct time'",
        "on time» означає «в домовлений або правильний час»",
    ),
    (
        "barely",
        "ледве",
        "He barely managed to finish his work on time",
        "Він ледве впорався із завершенням своєї роботи вчасно",
    ),
    (
        "shine",
        "сяяти",
        "The sun shone brightly on the clear morning",
        "Сонце яскраво сяяло ясним ранком",
    ),
    (
        "subtract",
        "віднімати",
        "He subtracted the numbers to find the correct result",
        "Він відняв числа, щоб отримати правильний результат",
    ),
    # (
    #     "strip, bark",
    #     "знімати, кора",
    #     "They stripped the bark from the tree carefully",
    #     "Вони обережно зняли кору з дерева",
    # ),
    (
        "tip, spill",
        "перекидати, проливати",
        "She accidentally tipped the glass, spilling the liquid",
        "Вона випадково перекинула склянку, проливши рідину",
    ),
    (
        "tip",
        "перекидати",
        "We haven't crossed the tipping point yet",
        "Ми ще не перетнули переломну точку",
    ),
    (
        "tip",
        "Наконечник",
        "With the tip of a powerful microscope we can actually move atoms",
        "Наконечником потужного мікроскопа ми дійсно можемо рухати атоми",
    ),
    (
        "tip",
        "порада",
        "But the secret ingredient for each tip has been time",
        "Але секретним інгредієнтом кожної поради був час",
    ),
    (
        "ladder",
        "драбина",
        "Just giving these guys the first step on the ladder",
        "Просто давши цим хлопцям перший крок на сходах",
    ),
    (
        "swallow, pill, gulp",
        "ковтати, таблетка, ковток",
        "He swallowed the pill with a gulp of water",
        "Він проковтнув таблетку ковтком води",
    ),
    (
        "trace",
        "відстежувати",
        "She traced her steps to find the lost keys",
        "Вона відстежила свої кроки, щоб знайти втрачені ключі",
    ),
    (
        "trace",
        "обвести",
        "carefully trace around the outside",
        "ретельно обведіть зовнішню сторону",
    ),
    # (
    #     "thirst, quench",
    #     "спрага, вгамувати",
    #     "In the heat, they drank water quickly to quench their thirst",
    #     "У спеку вони швидко пили воду, щоб вгамувати спрагу",
    # ),
    (
        "cheque, due",
        "чек, належно",
        "He signed the cheque for the amount due",
        "Він підписав чек на належну суму",
    ),
    (
        "due",
        "належно",
        "he attracts more criticism than is his due",
        "він викликає більше критики, ніж йому належить",
    ),
    (
        "due",
        "очікувана",
        "the baby's due in August",
        "дитина очікується в Серпні",
    ),
    (
        "weigh, scale, exact",
        "зважувати, ваги, точний",
        "The vendor weighed the fruit on the scale to get the exact price",
        "Продавець зважив фрукти на вагах, щоб отримати точну ціну",
    ),
    (
        "weigh",
        "співвідносити",
        "How do you weigh that with what you were just talking about?",
        "Як ви співвідносите це з тим, про що ви щойно говорили?",
    ),
    (
        "supply, charity, needy",
        "постачати, благодійність, нужденні",
        "The charity supplied food to the needy during the crisis",
        "Благодійна організація постачала їжу нужденним під час кризи",
    ),
    (
        "glance",
        "погляд",
        "She glanced at the clock and realized she was late",
        "Вона кинула погляд на годинник і зрозуміла, що запізнюється",
    ),
    (
        "coat, hang, hook, hallway",
        "пальто, вішати, гачок, коридор",
        "He hung his coat on the hook in the hallway",
        "Він повісив своє пальто на гачок у коридорі",
    ),
    (
        "wound, bleed, bandage",
        "рана, кровоточити, бинт",
        "The nurse bandaged the wound to stop the bleeding",
        "Медсестра забинтувала рану, щоб зупинити кровотечу",
    ),
    (
        "funeral, touching, tribute",
        "похорон, зворушливий, данина",
        "The touching speech at the funeral was a tribute to her life",
        "Зворушлива промова на похороні була даниною її життю",
    ),
    (
        "awakened, noise",
        "розбуджений, шум",
        "He was awakened by the noise in the middle of the night",
        "Він був розбуджений шумом посеред ночі",
    ),
    (
        "descend",
        "спускатися",
        "And then war and chaos descend",
        "А потім війна та хаос вщухають",
    ),
    (
        "descend",
        "спускатися",
        "Descend from heaven to sinful earth",
        "Спуститься з небес на грішну землю",
    ),
    (
        "descend",
        "спускатися",
        "Syria may descend into a civil war",
        "Сирія може впасти у громадянську війну",
    ),
    # (
    #     "descend, mountain, safely, guide",
    #     "спускатися, гора, безпечно, гід",
    #     "The hikers descended the mountain safely with the help of a guide",
    #     "Туристи безпечно спустилися з гори за допомогою гіда",
    # ),
    # ^--
    # 5 part
    (
        "rival, defeat",
        "суперник, поразка",
        "The rival faced defeat after their victory",
        "Суперник зазнав поразки після їхньої перемоги",
    ),
    (
        "aged, resident",
        "літній, мешканець",
        "The aged resident enjoyed his peaceful house",
        "Літній мешканець насолоджувався своїм спокійним будинком",
    ),
    (
        "resident, survive, injury",
        "мешканець, вижити, травма",
        "The home's resident survived her injury",
        "Мешканка дому вижила після своєї травми",
    ),
    (
        "boast",
        "хвалитися",
        "She liked to boast about her skill and success",
        "Їй подобалося хвалитися своєю майстерністю та успіхами",
    ),
    (
        "melt, bowl",
        "танути, чаша",
        "The ice began to melt in the bowl",
        "Лід почав танути в чаші",
    ),
    (
        "stocking, warmth",
        "панчоха, тепло",
        "She wore wool stockings for extra warmth",
        "Вона носила шерстяні панчохи для додаткового тепла",
    ),
    (
        "tough, challenge, overcome",
        "жорсткий, виклик, подолати",
        "The team faced a tough challenge but managed to overcome it",
        "Команда зіткнулася з жорстким викликом, але змогла його подолати",
    ),
    (
        "driving",
        "водіння",
        "He started driving as soon as he got his licence",
        "Він почав водити, як тільки отримав ліцензію",
    ),
    (
        "arise, opportunity",
        "виникати, можливість",
        "An opportunity may arise, so be ready to take it",
        "Може виникнути можливість, тому будьте готові скористатися нею",
    ),
    (
        "sick",
        "хворий",
        "The mother cared for her sick child",
        "Мати доглядала за своєю хворою дитиною",
    ),
    (
        "derive",
        "отримувати",
        "She derived much knowledge from that book",
        "Вона отримала багато знань із тієї книги",
    ),
    (
        "fee, due",
        "плата, підлягає оплаті - запланований",
        # у цьому прикладі
        # "due" позначає, що термін сплати збору за послугу вже минув.
        "The fee for the service was due yesterday",
        "Плата за послугу мала бути сплачена вчора",
    ),
    (
        "due",
        "підлягає оплаті - запланований",
        "The bill is due tomorrow",
        "Рахунок потрібно оплатити завтра",
    ),
    (
        "due",
        "підлягає оплаті - запланований",
        "She deserves due recognition for her work.",
        "Вона заслуговує на належне визнання за свою роботу",
    ),
    (
        "wrist",
        "зап'ястя",
        "She wore a silver bracelet on her wrist",
        "Вона носила срібний браслет на зап'ясті",
    ),
    (
        "pace",
        "темп",
        "They walked at a slow pace to relax",
        "Вони йшли повільним темпом, щоб розслабитися",
    ),
    (
        "allowance",
        "кишенькові гроші",
        "The child received a small weekly allowance",
        "Дитина отримувала невеликі щотижневі кишенькові гроші",
    ),
    (
        "contrary, opinion",
        "протилежний, думка",
        "He had a contrary opinion but decided to agree",
        "У нього була протилежна думка, але він вирішив погодитися",
    ),
    (
        "elderly",
        "літній",
        "The elderly couple spent time in their garden",
        "Літня пара проводила час у своєму саду",
    ),
    (
        "regard",
        "ставлення",
        "She regarded his advice as valuable",
        "Вона вважала його пораду цінною",
    ),
    (
        "seek",
        "шукати",
        "He sought the answer to his question",
        "Він шукав відповідь на своє питання",
    ),
    (
        "crease",
        "згин / складка",
        "The paper had a deep crease from being folded",
        "На папері був глибокий згин через складення",
    ),
    (
        "landing, stairs",
        "майданчик, сходи",
        "The landing at the top of the stairs was wide",
        "Майданчик на вершині сходів був широким",
    ),
    (
        "striking",
        "вражаючий",
        "The view from the top of the mountain was striking",
        "Вид з вершини гори був вражаючим",
    ),
    # (
    #     "housewife, chores",
    #     "домогосподарка, робота по дому",
    #     "The housewife completed her chores in the morning",
    #     "Домогосподарка виконала свою роботу по дому вранці",
    # ),
    (
        "ruling, court, judge",
        "рішення, суд, суддя",
        "The judge made a ruling in the court case",
        "Суддя виніс рішення у судовій справі",
    ),
    # (
    #     "county, fair, event",
    #     "графство, ярмарок, подія",
    #     "The county fair was the biggest event of the year",
    #     "Ярмарок у графстві був найбільшою подією року",
    # ),
    (
        "overall",
        "загальний",
        "The overall success of the plan was unexpected",
        "Загальний успіх плану був несподіваним",
    ),
    (
        "arm-chair, comfortable",
        "крісло, зручний",
        "He sat in a comfortable arm-chair while reading",
        "Він сидів у зручному кріслі, читаючи",
    ),
    (
        "syllable, pronounce",
        "склад слова, вимовляти",
        "Each syllable of the word was hard to pronounce",
        "Кожен склад цього слова було важко вимовити",
    ),
    (
        "injury, heal",
        "травма, загоюватися",
        "The athlete's injury took months to heal",
        "Травма атлета загоювалася місяцями",
    ),
    # (
    #     "injury",
    #     "травма",
    #     "The injury wasn't very dramatic or graphic",
    #     "Травма не була дуже серйозною або шокуючою",
    # ),
    (
        "threaten, undermine",
        "загрожувати, підривати",
        "Climate change threatens to undermine the entire infrastructure",
        "Зміна клімату загрожує підірвати всю інфраструктуру",
    ),
    (
        "harsh, undermine, effort, confidence",
        "суворий, підривати, зусилля, впевненість",
        "The harsh comments undermined his confidence",
        "Різкі коментарі підривали його впевненість",
    ),
    (
        "threaten, undermine",
        "погрожувати, підривати",
        "Her new husband threatened to undermine her rule",
        "Її новий чоловік погрожував підривати її правління",
    ),
    # ^--
]
