# flake8: noqa: E501

phrases = [
    # (
    #     "dexterous, trunk, doubles",
    #     "спритний, хобот, виконує подвійну функцію",
    #     "Her dexterous trunk doubles as a powerful, flexible arm",
    #     "Її спритний хобот служить також як потужная, гнучка рука",
    # ),
    # (
    #     "agile, appendages, bend, twist, contract, expand",
    #     "спритні, придатки, згинатися, крутитися, стискатися, розширюватися",
    #     "These agile appendages can bend, twist, contract, and expand",
    #     "Ці спритні придатки можуть згинатися, крутитися, стискатися та розширюватися",
    # ),
    #
    (
        "refusal",
        "відмова",
        "Her refusal to accept the favor surprised everyone",
        "Її відмова прийняти послугу здивувала всіх",
    ),
    (
        "refusal",
        "відмова",
        "Depression is an inability to feel or refusal to feel.",
        "Депресія - це нездатність відчувати або відмова відчувати.",
    ),
    (
        "refusal",
        "відмова",
        "It was a flat refusal to hold any meetings.",
        "Це була категорична відмова проводити будь-які зустрічі.",
    ),
    (
        "entertain",
        "розважати",
        "They decided to entertain the guests in the evening",
        "Вони вирішили розважити гостей увечері",
    ),
    (
        "entertain",
        "розважати",
        "If you're going to entertain yourself, do it with intent.",
        "Якщо ви збираєтеся розважити себе, робіть це з умислом.",
    ),
    # (
    #     "entertain",
    #     "розважати",
    #     "They are not unwilling to entertain a possibility of a military option.",
    #     "Вони не відмовляються від можливості військового варіанту.",
    # ),
    (
        "extreme, weather, damage",
        "екстремальний, погода, пошкодження",
        "The extreme weather caused significant damage to the crops",
        "Екстремальна погода завдала значної шкоди посівам",
    ),
    (
        "extreme",
        "екстремальний",
        "We would like to learn more about how organisms adapt to extreme environments.",
        "Ми б хотіли дізнатися більше про те, як організми адаптуються до екстремальних середовищ.",
    ),
    (
        "ought, obey",
        "повинен, підкорятися",
        "You ought to obey the rules for everyone's safety",
        "Ти повинен підкорятися правилам для безпеки всіх",
    ),
    (
        "ought",
        "повинен",
        "That's something we ought to celebrate.",
        "Це те, що ми повинні відсвяткувати.",
    ),
    (
        "ought",
        "повинен",
        "we ought not to begin without a proper plan.",
        "ми не повинні починати без належного плану.",
    ),
    # figure out together what we ought to do in order to preserve each other's wellbeing.
    (
        "sink",
        "мийка",
        "The kitchen sink was full of dirty water",
        "Мийка на кухні була наповнена брудною водою",
    ),
    (
        "invention",
        "винахід",
        "This invention marked a major step in scientific progress",
        "Цей винахід позначив значний крок у науковому прогресі.",
    ),
    (
        "generous",
        "щедрий",
        "He gave a generous gift to his best friend",
        "Він зробив щедрий подарунок своєму найкращому другу",
    ),
    (
        "generous",
        "щедрий",
        "the course exists thanks to the generous support of our patrons",
        "курс існує завдяки щедрій підтримці наших меценатів",
    ),
    (
        "seldom",
        "рідко",
        "We seldom visit the museum because it is far away",
        "Ми рідко відвідуємо музей, бо він далеко",
    ),
    (
        "seldom",
        "рідко",
        "I seldom find someone who has nothing to offer me.",
        "Я рідко знаходжу когось, кому нема чого мені запропонувати.",
    ),
    (
        "seldom",
        "рідко",
        "People are seldom interested in you and your actions as much as you think",
        "Люди рідко цікавляться вами і вашими вчинками так сильно, як вам здається",
    ),
    (
        "seldom",
        "рідко",
        "There seldom is a discussion about what is our mission",
        "Рідко виникає дискусія про те, яка наша місія",
    ),
    (
        "dish",
        "страва",
        "She prepared a delicious dish for dinner",
        "Вона приготувала смачну страву на обід",
    ),
    (
        "dish, gourmet",
        "страва, гурман",
        "Lobsters are considered a gourmet dish today",
        "Омари сьогодні вважаються вишуканою стравою",
    ),
    (
        "dish",
        "страва",
        "Place the pan in a large heavy baking dish",
        "Помістіть каструлю у велику важку форму для запікання",
    ),
    (
        "inquiry",
        "запит",
        "The police made an inquiry into the case",
        "Поліція зробила запит щодо справи",
    ),
    (
        "inquiry",
        "запит",
        "we're doing independent scientific inquiry",
        "ми проводимо незалежне наукове дослідження",
    ),
    (
        "inquiry",
        "запит",
        "The inquiry uncovered numerous problems.",
        "Розслідування виявило численні проблеми.",
    ),
    (
        "whereas",
        "тоді як",
        "She prefers coffee, whereas I prefer tea",
        "Вона віддає перевагу каві, тоді як я — чаю",
    ),
    (
        "whereas",
        "тоді як",
        "whereas the second word is usually stressed a bit more",
        "тоді як друге слово зазвичай наголошується трохи сильніше",
    ),
    (
        "rob",
        "грабувати",
        "The man tried to rob a bank but was caught by the police",
        "Чоловік спробував пограбувати банк, але його зловила поліція",
    ),
    (
        "rob",
        "грабувати",
        "Don't rob yourself of the best life you could live.",
        "Не позбавляйте себе найкращого життя, яке ви можете прожити.",
    ),
    (
        "rob",
        "грабувати",
        "They said the best way to rob a bank is to own one",
        "Кажуть, найкращий спосіб пограбувати банк — це володіти ним.",
    ),
    (
        "carriage, ride",
        "карета, їздити",
        "They enjoyed a carriage ride through the park",
        "Вони насолоджувалися поїздкою в кареті парком",
    ),
    (
        "pound",
        "фунт",
        "A pound is a common measure of weight",
        "Фунт — це поширена одиниця вимірювання ваги",
    ),
    (
        "tendency, increase",
        "тенденція, збільшувати",
        "There is a tendency for prices to increase every year",
        "Є тенденція до зростання цін щороку",
    ),
    (
        "straw",
        "солома",
        "She wore a straw hat on the sunny day",
        "Вона носила солом'яний капелюх у сонячний день",
    ),
    (
        "strip",
        "смужка",
        "He used a strip of cloth to clean the surface",
        "Він використав смужку тканини, щоб почистити поверхню",
    ),
    (
        "favorable, agreement",
        "сприятливий, угода",
        "The favorable conditions helped them reach an agreement",
        "Сприятливі умови допомогли їм досягти угоди",
    ),
    (
        "sweat",
        "піт",
        "He was covered in sweat after the hard exercise",
        "Він був вкритий потом після важких тренування",
    ),
    (
        "convince",
        "переконати",
        "She tried to convince her friend to join the plan",
        "Вона намагалася переконати друга приєднатися до плану",
    ),
    (
        "convince",
        "переконати",
        "You had to convince people to drink pasteurized milk",
        "Треба було переконати людей пити пастеризоване молоко",
    ),
    (
        "convince",
        "переконати",
        'Usually convince means "to cause (someone) to believe that something is true".',
        'Зазвичай "convince" означає "змусити (когось) повірити, що щось правдиве".',
    ),
    (
        "owe",
        "заборгувати",
        "He owes a lot of money to the bank",
        "Він заборгував багато грошей банку",
    ),
    (
        "neighbouring",
        "сусідній",
        "We often visit the neighbouring town on weekends",
        "Ми часто відвідуємо сусіднє місто у вихідні",
    ),
    (
        "rod",
        "стрижень",
        "He used a fishing rod by the river",
        "Він ловив рибу вудкою біля річки",
    ),
    (
        "nursery",
        "дитячий садок",
        "The nursery is full of happy children playing",
        "Дитячий садок наповнений щасливими дітьми, які грають",
    ),
    (
        "accordance, law",
        "відповідність, закон",
        "The decision was made in accordance with the law",
        "Рішення було прийнято відповідно до закону",
    ),
    (
        "significant",
        "значний",
        "The team made significant progress on the project",
        "Команда зробила значний прогрес у проєкті",
    ),
    (
        "challenge",
        "виклик",
        "There were some challenges in the project",
        "У проекті були певні труднощі.",
    ),
    (
        "furthermore, discuss",
        "більше того, обговорювати",
        "Furthermore, we need to discuss your ideas in detail",
        "Більше того, нам потрібно детально обговорити ваші ідеї",
    ),
    # ^furthermore
    (
        "sweat",
        "піт",
        "Hard work and sweat are necessary for success",
        "Наполеглива праця і піт необхідні для успіху",
    ),
    (
        "convince",
        "переконати",
        "She convinced the audience to support her idea",
        "Вона переконала аудиторію підтримати її ідею",
    ),
    (
        "owe",
        "заборгувати",
        "I still owe money to my friend for the tickets",
        "Я досі заборгував гроші своєму другу за квитки",
    ),
    (
        "neighbouring",
        "сусідній",
        "The neighbouring house belongs to a friendly family",
        "Сусідній будинок належить привітній сім'ї",
    ),
    # (
    #     "favor, help, request",
    #     "послуга, допомога, прохання",
    #     "He asked for a small favor to help him move",
    #     "Він попросив невелику послугу, щоб допомогти йому переїхати",
    # ),
    (
        "rod",
        "стрижень",
        "He used a fishing rod by the lake all afternoon",
        "Він ловив рибу вудкою біля озера весь день після обіду",
    ),
    (
        "nursery, variety",
        "розсадник, різноманітність",
        "The nursery grows a variety of plants for the garden",
        "Розсадник вирощує різноманітні рослини для саду",
    ),
    (
        "accordance",
        "відповідність",
        "The decision was made in accordance with the rules",
        "Рішення було прийнято відповідно до правил",
    ),
    (
        "significant, policy",
        "значний, політика",
        "The new policy included significant changes to the rules",
        "Нова політика включала значні зміни до правил",
    ),
    (
        "furthermore",
        "більше того",
        "Furthermore, I will explain the details in my next report",
        "Більше того, я поясню деталі у своєму наступному звіті",
    ),
    (
        "postage, stamp",
        "поштовий збір, марка",
        "The postage for sending the letter was quite low",
        "Поштовий збір за відправлення листа був досить низьким",
    ),
    (
        "thorough, inspection",
        "ретельний, перевірка",
        "The inspector conducted a thorough inspection of the site",
        "Інспектор провів ретельну перевірку об'єкта",
    ),
    (
        "argue",
        "сваритися",
        "They argued about the decision during the meeting",
        "Вони сперечалися щодо рішення під час зустрічі",
    ),
    (
        "crop, harvest",
        "урожай, збирання",
        "The crop was ready for harvest by the end of the season",
        "Урожай був готовий до збирання наприкінці сезону",
    ),
    (
        "chord",
        "акорд",
        "He played a beautiful chord on the guitar",
        "Він зіграв красивий акорд на гітарі",
    ),
    (
        "miner, coal",
        "шахтар, вугілля",
        "The miner worked hard to extract coal from the mine",
        "Шахтар наполегливо працював, щоб добути вугілля з шахти",
    ),
    (
        "steal, wallet, thief",
        "красти, гаманець, злодій",
        "The thief tried to steal her wallet but was caught",
        "Злодій намагався вкрасти її гаманець, але його зловили",
    ),
    (
        "significance",
        "значущість",
        "The significance of the event was clear to everyone",
        "Значущість події була зрозумілою для всіх",
    ),
    (
        "prayer, faith",
        "молитва, віра",
        "She said a prayer with hope and faith in her heart",
        "Вона промовила молитву з надією та вірою в серці",
    ),
    (
        "decline, politely",
        "відмовитися, ввічливо",
        "He declined the offer politely but firmly",
        "Він ввічливо, але рішуче відмовився від пропозиції",
    ),
    (
        "offence, remark, apology",
        "образа, зауваження, вибачення",
        "Her remark caused offence, but she quickly apologized",
        "Її зауваження спричинило образу, але вона швидко вибачилася",
    ),
    (
        "stir",
        "помішувати",
        "She used a wooden spoon to stir the pot of soup",
        "Вона використовувала дерев'яну ложку, щоб помішувати каструлю з супом",
    ),
    (
        "obey",
        "підкорятися",
        "The students were expected to obey the rules set by the teacher",
        "Від учнів очікувалося дотримання правил, встановлених учителем",
    ),
    # (
    #     "verse, poem, rhyme",
    #     "вірш, поема, рима",
    #     "The last verse of the poem had a beautiful rhyme",
    #     "Останній вірш поеми мав красиву риму",
    # ),
    (
        "consideration",
        "увага",
        "She showed consideration for the feelings of others",
        "Вона виявила увагу до почуттів інших",
    ),
    # (
    #     "consideration",
    #     "увага",
    #     "",
    #     "",
    # ),
    # (
    #     "consideration",
    #     "увага",
    #     "",
    #     "",
    # ),
    (
        "compound",
        "складний",
        "The compound word had a unique meaning",
        "Складне слово мало унікальне значення",
    ),
    (
        "fasten, securely",
        "пристебнути, надійно",
        "Please fasten your seat belt securely before takeoff",
        "Будь ласка, надійно пристебніть ремінь безпеки перед зльотом",
    ),
    (
        "devote",
        "присвятити",
        "She devoted her time to taking care of her family",
        "Вона присвятила свій час догляду за сім'єю",
    ),
    (
        "continuity",
        "неперервність",
        "The continuity of the project was key to its success",
        "Неперервність проєкту була ключем до його успіху",
    ),
    (
        "worst",
        "найгірший",
        "His worst fear became a reality during the storm",
        "Його найгірший страх став реальністю під час бурі",
    ),
    (
        "relieve",
        "полегшити",
        "The medicine helped relieve her pain quickly",
        "Ліки допомогли швидко полегшити її біль",
    ),
    (
        "admire",
        "милуватися / захоплюватися",
        "We stopped to admire the beauty of nature",
        "Ми зупинилися, щоб помилуватися красою природи",
    ),
    (
        "admire, precisely",
        "милуватися / захоплюватися, точно",
        "We admire beautiful code precisely because it isn't easy to do",
        "Ми захоплюємося красивим кодом саме тому, що це непросто зробити",
    ),
    (
        "admire, spectacle",
        "милуватися / захоплюватися, видовище",
        "Visitors can admire the amazing architectural spectacle",
        "Відвідувачі можуть помилуватися дивовижним архітектурним видовищем",
    ),
    # (
    #     "leap, fence, yard",
    #     "стрибок, паркан, двір",
    #     "The dog made a leap over the fence into the yard",
    #     "Собака стрибнув через паркан у двір",
    # ),
    (
        "deserve, praise",
        "заслуговувати, похвала",
        "Her effort to help the team deserves praise",
        "Її зусилля допомогти команді заслуговують похвали",
    ),
    # (
    #     "decisive, leader, action",
    #     "рішучий, лідер, дія",
    #     "The leader took decisive action to solve the problem",
    #     "Лідер прийняв рішуче рішення, щоб вирішити проблему",
    # ),
    # (
    #     "observe, stars, night",
    #     "спостерігати, зірки, ніч",
    #     "They observed the stars through a telescope at night",
    #     "Вони спостерігали за зірками через телескоп уночі",
    # ),
    # (
    #     "peculiar, habit, person",
    #     "дивний, звичка, людина",
    #     "He has a peculiar habit of talking to himself",
    #     "У нього є дивна звичка говорити сам із собою",
    # ),
    # (
    #     "quarrel, family, argument",
    #     "сварка, сім'я, аргумент",
    #     "A small argument turned into a family quarrel",
    #     "Маленький аргумент перетворився на сімейну сварку",
    # ),
    # (
    #     "prefer, coffee, tea",
    #     "віддавати перевагу, кава, чай",
    #     "She prefers coffee over tea in the mornings",
    #     "Вона надає перевагу каві, а не чаю вранці",
    # ),
    # (
    #     "urge, friend, decision",
    #     "закликати, друг, рішення",
    #     "I urged my friend to make a wise decision",
    #     "Я закликав свого друга прийняти розумне рішення",
    # ),
    # (
    #     "rarely, meet, neighbor",
    #     "рідко, зустрічати, сусід",
    #     "We rarely meet our neighbor these days",
    #     "Ми рідко зустрічаємо свого сусіда останнім часом",
    # ),
    # (
    #     "apparent, mistake, work",
    #     "очевидний, помилка, робота",
    #     "The mistake in the report was quite apparent",
    #     "Помилка в звіті була досить очевидною",
    # ),
    # (
    #     "vanish, fog, morning",
    #     "зникати, туман, ранок",
    #     "The fog will vanish as the morning sun rises",
    #     "Туман зникне, коли зійде ранкове сонце",
    # ),
    # (
    #     "doubt, decision, result",
    #     "сумнів, рішення, результат",
    #     "There is no doubt that this decision will bring good results",
    #     "Немає сумнівів, що це рішення принесе хороші результати",
    # ),
    # (
    #     "trace, path, forest",
    #     "слід, шлях, ліс",
    #     "We followed the trace of footsteps along the forest path",
    #     "Ми слідували слідам на лісовій стежці",
    # ),
    # (
    #     "alter, plan, situation",
    #     "змінювати, план, ситуація",
    #     "The team had to alter their plan due to the situation",
    #     "Команді довелося змінити свій план через ситуацію",
    # ),
    # (
    #     "frequent, visits, friends",
    #     "частий, візити, друзі",
    #     "Her frequent visits to her friends kept her happy",
    #     "Її часті візити до друзів робили її щасливою",
    # ),
    # (
    #     "retain, knowledge, study",
    #     "зберігати, знання, навчання",
    #     "He retained most of the knowledge from his studies",
    #     "Він зберіг більшість знань зі свого навчання",
    # ),
    # (
    #     "bright, future, hope",
    #     "яскравий, майбутнє, надія",
    #     "They are working hard for a bright future full of hope",
    #     "Вони старанно працюють заради яскравого майбутнього, сповненого надії",
    # ),
    # (
    #     "provide, shelter, animal",
    #     "забезпечувати, прихисток, тварина",
    #     "The shelter provides a safe place for abandoned animals",
    #     "Притулок забезпечує безпечне місце для покинутих тварин",
    # ),
]
