# flake8: noqa: E501

phrases = [
    # peers, casual
    # For your peers, try to go more casual.
    # Для своїх однолітків намагайтеся бути більш повсякденними.
    (
        "advert, carpet, site",
        "реклама, килим, місце",
        "The advert showed a beautiful carpet for the new site.",
        "Реклама показала красивий килим для нового місця.",
    ),
    (
        "goat, collar, grown-up",
        "козел, нашийник, дорослий",
        "The grown-up put a collar on the goat.",
        "Дорослий надів нашийник на козла.",
    ),
    (
        "collar, wage, declined",
        "нашийник, зарплата, зменшилися",
        "Our jobs have been stolen, and blue collar wages have declined.",
        "Наші робочі місця були вкрадені, і зарплати синіх комірців зменшилися.",
    ),
    (
        "collar, closure",
        "нашийник, закриття",
        "Many blue-collar jobs were lost due to factory closures.",
        "Багато робочих місць синіх комірців було втрачено через закриття заводів.",
    ),
    (
        "collar, shortage",
        "нашийник, нестача",
        "we are suffering a shortage of highly skilled blue collar workers",
        # "ми відчуваємо брак висококваліфікованих робітників",
        "Ми страждаємо від нестачі висококваліфікованих працівників фізичної праці.",
    ),
    (
        "poverty, relief, loan",
        "бідність, полегшення, кредит",
        "The loan brought relief to the family in poverty.",
        "Кредит приніс полегшення сім’ї, яка жила в бідності.",
    ),
    # (
    #     "trunk, drag, rubber",
    #     "багажник, тягнути, гумовий",
    #     "They dragged the rubber mat out of the car trunk.",
    #     "Вони витягнули гумовий килимок із багажника машини.",
    # ),
    (
        "trunk, negotiate",
        "стовбур, долати",
        "Even a bear cub negotiates the trunk like a power lineman.",
        "Навіть ведмежа долає стовбур дерева, як електромонтер.",
    ),
    (
        "treaty, negotiate",
        "договір, вести переговори",
        "Diplomats from both countries tried to negotiate a peace treaty",
        "Дипломати з обох країн намагалися вести переговори про мирний договір",
    ),
    (
        "negotiation",
        "переговори",
        "Everything in life is a negotiation.",
        "Все в житті - це переговори.",
    ),
    (
        "barrel, tap, mere",
        "бочка, дотик, простий",
        "A mere tap on the barrel released the water.",
        "Лише дотик до бочці випустило воду.",
    ),
    (
        "chamber, temple, judgement",
        "камера, храм, судження",
        "The old chamber near the temple was quiet for judgement.",
        "Стара камера біля храму була тиха для роздумів.",
    ),
    (
        "fighter, ray, judgement",
        "боєць, промінь, судження",
        "The fighter saw a ray of hope in the final judgement.",
        "Боєць побачив промінь надії у фінальному рішенні.",
    ),
    (
        "loan, estate, quarter",
        "кредит, маєток, квартал",
        "He took a loan to buy an estate in the quarter.",
        "Він взяв кредит, щоб купити маєток у кварталі.",
    ),
    (
        "assess, excessive, backward",
        "оцінювати, надмірний, назад",
        "They assessed the excessive costs of moving backward.",
        "Вони оцінили надмірні витрати на рух назад.",
    ),
    (
        "screw, chamber, rubber, seal",
        "гвинт, камера, гумовий, ущільнення",
        "The rubber seal was fixed with a screw in the chamber.",
        "Гумову прокладку закріпили гвинтом у камері.",
    ),
    (
        "seal",
        "ущільнення",
        "They want to seal the deal quickly.",
        "Вони хочуть швидко укласти угоду.",
    ),
    (
        "waist, skirt, niece",
        "талія, спідниця, племінниця",
        "Her niece wore a skirt tied tightly at the waist.",
        "Її племінниця одягнула спідницю, щільно зав’язану на талії.",
    ),
    (
        "undertake, sensible",
        "взяти на себе, розумний",
        "He decided to undertake a sensible task to help his team.",
        "Він вирішив взяти на себе розумне завдання, щоб допомогти своїй команді.",
    ),
    (
        "inquire, loan, affair",
        "дізнаватися, кредит, справа",
        "She inquired about the loan for her business affair.",
        "Вона дізналася про кредит для своєї справи.",
    ),
    (
        "drag, barrel, site",
        "тягнути, бочка, місце",
        "They dragged the barrel to the new site.",
        "Вони потягнули бочку на нове місце.",
    ),
    (
        "fighter, strengthen, judgement",
        "боєць, зміцнювати, судження",
        "The fighter tried to strengthen his mind before the judgement.",
        "Боєць намагався зміцнити свій розум перед вироком.",
    ),
    (
        "poverty, chamber, estate",
        "бідність, камера, маєток",
        "The estate owner built a chamber to help fight poverty.",
        "Власник маєтку побудував кімнату для боротьби з бідністю.",
    ),
    (
        "splendid, ray, temple",
        "чудовий, промінь, храм",
        "A splendid ray of light entered the old temple.",
        "Чудовий промінь світла увійшов до старого храму.",
    ),
    # (
    #     "imply, notion, judgement",
    #     "натякати, поняття, судження",
    #     "His notion seemed to imply a harsh judgement.",
    #     "Його поняття, здавалося, натякало на суворе судження.",
    # ),
    (
        "throw",
        "кинути",
        "They always throw loaded parties",
        "Вони завжди влаштовують насичені вечірки",
    ),
    (
        "notion",
        "поняття",
        "I was attracted to that notion of limitless possibility.",
        "Мене привабило це поняття безмежних можливостей.",
    ),
    (
        "notion",
        "поняття",
        "some people may share that same notion",
        "Деякі люди можуть поділяти ту саму думку.",
    ),
    (
        "notion, throw",
        "поняття, кинути",
        "Take the notion of, you threw a party and nobody showed up.",
        "Уявіть собі ситуацію, що ви влаштували вечірку, і ніхто не з'явився.",
    ),
    (
        "imply",
        "означати",
        "These findings imply that cigarette placements raise sales",
        "Ці висновки означають, що розміщення сигарет підвищує продажі.",
    ),
    # (
    #     "imply",
    #     "мати на увазі",
    #     "I don't wanna imply that it's strictly personal",
    #     "Я не хочу сказати, що це суто особисте",
    # ),
    (
        "imply",
        "означати",
        "This would imply the complete absence of the government.",
        "Це означало б повну відсутність уряду.",
    ),
    (
        "imply",
        "означати",
        "I don't mean to imply that you made a mistake.",
        "Я не маю на увазі, що ви зробили помилку.",
    ),
    (
        "imply",
        "означати",
        "Close relationships imply pain.",
        "Близькі стосунки передбачають біль.",
    ),
    (
        "loose, collar, servant",
        "нетугий, нашийник, слуга",
        "The servant adjusted the loose collar of his shirt.",
        "Слуга поправив вільний комір своєї сорочки.",
    ),
    (
        "debt, rubber, quarter",
        "борг, гумовий, квартал",
        "He paid his debt by selling rubber goods in the quarter.",
        "Він погасив свій борг, продаючи гумові вироби у кварталі.",
    ),
    (
        "estate, assess",
        "маєток, оцінити",
        "They hired an expert to assess the value of the estate.",
        "Вони найняли експерта, щоб оцінити вартість маєтку.",
    ),
    (
        "rubber, trunk, drag",
        "гумовий, багажник, тягнути",
        "He dragged the rubber mat out of the car trunk.",
        "Він витягнув гумовий килимок із багажника машини.",
    ),
    (
        "barrel, pour",
        "бочка, наливати",
        "They poured the wine carefully from the barrel.",
        "Вони обережно наливали вино з бочки.",
    ),
    (
        "splendid, grown-up, affair",
        "чудовий, дорослий, справа",
        "The grown-up managed a splendid affair for the family.",
        "Дорослий організував чудову справу для родини.",
    ),
    (
        "debt, mere, notion",
        "борг, простий, поняття",
        "The mere notion of debt made him anxious.",
        "Сама думка про борг викликала в нього тривогу.",
    ),
    (
        "backward, loose, screw",
        "назад, нетугий, гвинт",
        "Turn the screw backward to loosen it.",
        "Поверніть гвинт назад, щоб послабити його.",
    ),
    (
        "poverty, excessive, relief",
        "бідність, надмірний, полегшення",
        "Excessive relief programs helped reduce poverty.",
        "Надмірні програми допомоги допомогли зменшити бідність.",
    ),
    (
        "chamber, quarter, servant",
        "камера, квартал, слуга",
        "The servant cleaned the chamber in the old quarter.",
        "Слуга прибрав кімнату у старому кварталі.",
    ),
    (
        "advert, sensible, skirt",
        "реклама, розумний, спідниця",
        "The advert showed a sensible price for the skirt.",
        "Реклама показала розумну ціну на спідницю.",
    ),
    (
        "waist, loose",
        "талія, нетугий",
        "The belt was loose around her waist.",
        "Пояс був вільним на її талії.",
    ),
    (
        "lung, injure, fighter",
        "легеня, поранити, боєць",
        "The fighter injured his lung during the match.",
        "Боєць поранив легеню під час поєдинку.",
    ),
    # (
    #     "ray, chamber, site",
    #     "промінь, камера, місце",
    #     "A ray of sunlight lit the chamber at the site.",
    #     "Промінь сонця освітлив кімнату на місці.",
    # ),
    (
        "waist, skirt, splendid",
        "талія, спідниця, чудовий",
        "The splendid skirt fit perfectly around her waist.",
        "Чудова спідниця ідеально сиділа на її талії.",
    ),
    (
        "loose, collar, drag",
        "нетугий, нашийник, тягнути",
        "He dragged the loose collar back into place.",
        "Він підтягнув вільний комір на місце.",
    ),
    (
        "debt, affair, assess",
        "борг, справа, оцінювати",
        "They assessed the debt involved in the business affair.",
        "Вони оцінили борг, пов'язаний із бізнес-справою.",
    ),
    (
        "rubber, screw, trunk",
        "гумовий, гвинт, багажник",
        "The trunk was secured with a rubber screw.",
        "Багажник був закріплений гумовим гвинтом.",
    ),
    (
        "poverty, eliminate, relief",
        "бідність, усувати, полегшення",
        "Programs aim to eliminate poverty and bring relief.",
        "Програми спрямовані на усунення бідності та полегшення.",
    ),
    (
        "splendid, niece, grown-up",
        "чудовий, племінниця, дорослий",
        "Her niece gave a splendid speech for the grown-ups.",
        "Її племінниця виголосила чудову промову для дорослих.",
    ),
    # (
    #     "temple, ray, sensible",
    #     "храм, промінь, розумний",
    #     "A ray of light entered the temple through a sensible design.",
    #     "Промінь світла увійшов у храм через продуманий дизайн.",
    # ),
    (
        "quarter, site, drag",
        "квартал, місце, тягнути",
        "They dragged the materials to the construction site in the quarter.",
        "Вони потягнули матеріали на будівельний майданчик у кварталі.",
    ),
    (
        "undertake, affair, sensible",
        "взяти на себе, справа, розумний",
        "He decided to undertake the affair with a sensible approach.",
        "Він вирішив взятися за справу з розумним підходом.",
    ),
    (
        "chamber, temple, splendid",
        "кімната, храм, чудовий",
        "The chamber inside the temple had a splendid design.",
        "Кімната всередині храму мала чудовий дизайн.",
    ),
    (
        "advert, debt, poverty",
        "реклама, борг, бідність",
        "The advert focused on helping families in debt and poverty.",
        "Реклама була спрямована на допомогу сім'ям у боргах і бідності.",
    ),
    (
        "rubber, barrel, quarter",
        "гумовий, бочка, квартал",
        "The rubber barrel was delivered to the shop in the quarter.",
        "Гумову бочку доставили до магазину в кварталі.",
    ),
    (
        "injure, fighter, judgement",
        "поранити, боєць, судження",
        "The fighter was injured, but his judgement remained sharp.",
        "Боєць був поранений, але його судження залишалися гострими.",
    ),
    (
        "estate, assess",
        "маєток, оцінювати",
        "They assessed the value of the old estate.",
        "Вони оцінили вартість старого маєтку.",
    ),
    (
        "waist, loose, skirt",
        "талія, нетугий, спідниця",
        "The skirt was loose around her waist and needed adjustments.",
        "Спідниця була вільною на її талії та потребувала підгонки.",
    ),
    (
        "splendid, ray, grown-up",
        "чудовий, промінь, дорослий",
        "A splendid ray of sunlight brightened the room for the grown-ups.",
        "Чудовий промінь сонячного світла освітив кімнату для дорослих.",
    ),
    (
        "poverty, relief, loan",
        "бідність, полегшення, кредит",
        "The loan provided relief for the family struggling with poverty.",
        "Кредит приніс полегшення сім'ї, яка боролася з бідністю.",
    ),
    (
        "drag, site, collar, loose",
        "тягнути, місце, нашийник, нетугий",
        "He dragged the box to the site, fixing his loose collar on the way.",
        "Він потягнув коробку до місця, поправляючи свій вільний комір по дорозі.",
    ),
    (
        "oppose",
        "протистояти",
        "She opposed the decision strongly during the meeting.",
        "Вона сильно протистояла рішенню під час зустрічі.",
    ),
    (
        "bury",
        "закопувати",
        "They buried the treasure deep in the ground.",
        "Вони закопали скарб глибоко в землю.",
    ),
    (
        "assessment",
        "оцінка",
        "The assessment of the property’s value was completed yesterday.",
        "Оцінка вартості майна була завершена вчора.",
    ),
    (
        "merely, suggestion",
        "лише, пропозиція",
        "It was merely a suggestion, not a final opinion.",
        "Це була лише пропозиція, а не остаточна думка.",
    ),
    (
        "dealer",
        "дилер",
        "The car dealer introduced several new models.",
        "Дилер автомобілів представив кілька нових моделей.",
    ),
    (
        "backward",
        "назад",
        "He took a step backward carefully to avoid falling.",
        "Він обережно зробив крок назад, щоб не впасти.",
    ),
    (
        "forbid",
        "забороняти",
        "The rules forbid smoking in this room.",
        "Правила забороняють куріння в цій кімнаті.",
    ),
    (
        "rank",
        "звання",
        "The soldier was promoted to the rank of officer.",
        "Солдат був підвищений до звання офіцера.",
    ),
    (
        "literary",
        "літературний",
        "Her literary works are famous worldwide.",
        "Її літературні твори відомі по всьому світу.",
    ),
    (
        "blow",
        "удар",
        "The wind blew his hat off his head.",
        "Вітер здув його капелюх із голови.",
    ),
    (
        "oppose",
        "протистояти",
        "He opposed the idea firmly during the discussion.",
        "Він твердо протистояв цій ідеї під час обговорення.",
    ),
    (
        "bury",
        "закопувати",
        "She wanted to bury her past completely and start fresh.",
        "Вона хотіла повністю поховати своє минуле і почати спочатку.",
    ),
    (
        "assessment, launch",
        "оцінка, запуск",
        "The assessment of the risks delayed the project launch.",
        "Оцінка ризиків затримала запуск проєкту.",
    ),
    (
        "merely, statement",
        "лише, твердження",
        "It was merely a statement to clarify the situation.",
        "Це було лише твердження для уточнення ситуації.",
    ),
    (
        "conclude",
        "заключити",
        "The book concludes with an exciting final chapter.",
        "Книга завершується захоплюючим фінальним розділом.",
    ),
    (
        "conclude",
        "заключити",
        "They concluded the meeting quickly due to time constraints.",
        "Вони швидко завершили зустріч через обмеження в часі.",
    ),
    (
        "conclude",
        "заключити",
        "we can conclude that the universe is full of life",
        "ми можемо зробити висновок, що Всесвіт сповнений життя",
    ),
    (
        "conclude",
        "заключити",
        "We have reason to conclude that further investigation is necessary.",
        "У нас є підстави зробити висновок про необхідність подальшого розслідування.",
    ),
    (
        "dealer",
        "дилер",
        "The art dealer displayed a rare collection at the gallery.",
        "Дилер мистецтва представив рідкісну колекцію в галереї.",
    ),
    (
        "cast, backward, glance, regret",
        "кинути, назад, погляд, жаль",
        "He cast a backward glance full of regret before leaving.",
        "Він кинув назад погляд, повний жалю, перед тим як піти.",
    ),
    (
        "forbid",
        "забороняти",
        "The sign forbids entry to the dangerous area.",
        "Знак забороняє вхід до небезпечної зони.",
    ),
    (
        "rank",
        "звання",
        "The officer held a high rank in the military.",
        "Офіцер займав високе звання у військових силах.",
    ),
    (
        "literary",
        "літературний",
        "The literary society held a meeting to discuss new books.",
        "Літературне товариство провело зустріч для обговорення нових книг.",
    ),
    (
        "blow",
        "удар",
        "The wind blew out the candle during the storm.",
        "Вітер задмухнув свічку під час бурі.",
    ),
    # (
    #     "advert, carpet, dealer, welfare",
    #     "оголошення, килим, дилер, добробут",
    #     "The dealer placed an advert about a new carpet for welfare purposes.",
    #     "Дилер розмістив оголошення про новий килим із метою добробуту.",
    # ),
    # (
    #     "goat, collar, tap, screw",
    #     "коза, нашийник, кран, гвинт",
    #     "He fixed the tap with a screw and tied the goat's collar.",
    #     "Він полагодив кран гвинтом і зав'язав нашийник кози.",
    # ),
    # (
    #     "fighter, ray, chamber, strength",
    #     "боєць, промінь, камера, сила",
    #     "The fighter saw a ray of light entering the chamber, giving him strength.",
    #     "Боєць побачив промінь світла, що проникав у камеру, і це дало йому сили.",
    # ),
    # (
    #     "mere, notion, barrel, relief",
    #     "просто, поняття, барель, полегшення",
    #     "The mere notion of finding a full barrel brought relief to the villagers.",
    #     "Просто ідея знайти повний барель принесла полегшення селянам.",
    # ),
    # (
    #     "pour, rubber, lung, excessive",
    #     "наливати, гума, легеня, надмірний",
    #     "Excessive pouring of rubber fumes affected his lungs.",
    #     "Надмірне виливання гумових випарів вплинуло на його легені.",
    # ),
    # (
    #     "inquire, niece, skirt, temple",
    #     "запитати, племінниця, спідниця, храм",
    #     "She inquired about her niece's blue skirt near the temple.",
    #     "Вона запитала про блакитну спідницю своєї племінниці біля храму.",
    # ),
    # (
    #     "poverty, assess, servant, grown-up",
    #     "бідність, оцінювати, слуга, дорослий",
    #     "The grown-up servant assessed the impact of poverty on the children.",
    #     "Дорослий слуга оцінив вплив бідності на дітей.",
    # ),
    # (
    #     "loan, estate, drag, backward",
    #     "позика, маєток, тягнути, назад",
    #     "He took a loan to buy an estate and started dragging furniture backward.",
    #     "Він взяв позику на купівлю маєтку і почав тягнути меблі назад.",
    # ),
    # (
    #     "waist, judgement, imply, loose",
    #     "талія, судження, натякати, вільний",
    #     "Her loose dress implied a focus on comfort rather than a slim waist, showing good judgement.",
    #     "Її вільна сукня натякала на комфорт, а не на вузьку талію, демонструючи гарне судження.",
    # ),
    # (
    #     "affair, trunk, grown-up, chamber",
    #     "справа, стовбур, дорослий, камера",
    #     "The grown-up hid the affair documents in the trunk inside the chamber.",
    #     "Дорослий сховав документи справи в стовбурі всередині камери.",
    # ),
]
